FROM python:3.10-bullseye

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get clean && apt-get update && apt-get install -y gdal-bin supervisor && rm -rf /var/lib/apt/lists/*

RUN pip install poetry

WORKDIR /app/

COPY config/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

COPY poetry.lock pyproject.toml /app/
RUN poetry install

COPY . /app/

CMD ["/usr/bin/supervisord"]
