# Digital Ocean App Platform

FROM python:3.10-bullseye

RUN apt-get update && apt-get install -y gdal-bin npm

RUN pip install poetry

WORKDIR /app/
COPY poetry.lock pyproject.toml /app/
RUN poetry install

COPY package.json package-lock.json /app/
RUN npm install

COPY . /app/

ENV SECRET_KEY=f
RUN make build-static
RUN poetry run ./manage.py collectstatic --noinput
