# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 04:23
from __future__ import unicode_literals

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminArea',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('atco_code', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=48)),
                ('short_name', models.CharField(max_length=48)),
                ('country', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=48)),
                ('admin_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstops.AdminArea')),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=48)),
                ('qualifier_name', models.CharField(blank=True, max_length=48)),
                ('easting', models.PositiveIntegerField()),
                ('northing', models.PositiveIntegerField()),
                ('admin_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstops.AdminArea')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='busstops.District')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='StopPoint',
            fields=[
                ('atco_code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('naptan_code', models.CharField(max_length=16)),
                ('common_name', models.CharField(max_length=48)),
                ('landmark', models.CharField(max_length=48)),
                ('street', models.CharField(max_length=48)),
                ('crossing', models.CharField(max_length=48)),
                ('indicator', models.CharField(max_length=48)),
                ('latlong', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('suburb', models.CharField(max_length=48)),
                ('town', models.CharField(max_length=48)),
                ('locality_centre', models.BooleanField()),
                ('bearing', models.CharField(choices=[(b'N', b'north'), (b'NE', b'north east'), (b'E', b'east'), (b'SE', b'south east'), (b'S', b'south'), (b'SW', b'south west'), (b'W', b'west'), (b'NW', b'north west')], max_length=2)),
                ('stop_type', models.CharField(max_length=3)),
                ('bus_stop_type', models.CharField(max_length=3)),
                ('timing_status', models.CharField(max_length=3)),
                ('active', models.BooleanField()),
                ('admin_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstops.AdminArea')),
                ('locality', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='busstops.Locality')),
            ],
        ),
        migrations.AddField(
            model_name='adminarea',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstops.Region'),
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('parent', models.CharField(blank=True, max_length=48)),
                ('vehicle_mode', models.CharField(blank=True, max_length=48)),
                ('region', models.ForeignKey(default='GB', on_delete=django.db.models.deletion.CASCADE, to='busstops.Region')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_code', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('stops', models.ManyToManyField(editable=False, to=b'busstops.StopPoint')),
                ('operator', models.ManyToManyField(blank=True, to=b'busstops.Operator')),
                ('description', models.CharField(max_length=128)),
                ('line_name', models.CharField(max_length=64)),
                ('mode', models.CharField(max_length=11)),
                ('net', models.CharField(blank=True, max_length=3)),
                ('date', models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0))),
                ('region', models.ForeignKey(default='GB', on_delete=django.db.models.deletion.CASCADE, to='busstops.Region')),
                ('current', models.NullBooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='locality',
            name='parent',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='busstops.Locality'),
        ),
        migrations.CreateModel(
            name='StopArea',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=48)),
                ('stop_area_type', models.CharField(choices=[(b'GPBS', b'on-street pair'), (b'GCLS', b'on-street cluster'), (b'GAIR', b'airport building'), (b'GBCS', b'bus/coach station'), (b'GFTD', b'ferry terminal/dock'), (b'GTMU', b'tram/metro station'), (b'GRLS', b'rail station'), (b'GCCH', b'coach service coverage')], max_length=4)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=27700)),
                ('active', models.BooleanField()),
                ('admin_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstops.AdminArea')),
                ('parent', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='busstops.StopArea')),
            ],
        ),
        migrations.AddField(
            model_name='stoppoint',
            name='stop_area',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='busstops.StopArea'),
        ),
        migrations.RemoveField(
            model_name='locality',
            name='easting',
        ),
        migrations.RemoveField(
            model_name='locality',
            name='northing',
        ),
        migrations.AddField(
            model_name='locality',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=27700),
        ),
        migrations.AddField(
            model_name='stoppoint',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=27700),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='active',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='adjancent',
            field=models.ManyToManyField(related_name='neighbour', to=b'busstops.Locality'),
        ),
    ]
