# Generated by Django 3.1.1 on 2020-09-30 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecolour',
            name='operator',
        ),
        migrations.AddField(
            model_name='operator',
            name='colour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.servicecolour'),
        ),
        migrations.AddField(
            model_name='operator',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='operators', to='busstops.Region'),
        ),
        migrations.AddField(
            model_name='operator',
            name='siblings',
            field=models.ManyToManyField(blank=True, related_name='_operator_siblings_+', to='busstops.Operator'),
        ),
        migrations.AddField(
            model_name='servicecolour',
            name='border',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='operator',
            name='parent',
            field=models.CharField(blank=True, db_index=True, max_length=48),
        ),
        migrations.AlterField(
            model_name='operator',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.region'),
        ),
    ]
