# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='show_timetable',
            field=models.BooleanField(default=False),
        ),
    ]
