# Generated by Django 3.0.7 on 2020-06-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='assistance_service',
        ),
        migrations.RemoveField(
            model_name='service',
            name='low_floor',
        ),
        migrations.RemoveField(
            model_name='service',
            name='mobility_scooter',
        ),
        migrations.RemoveField(
            model_name='service',
            name='wheelchair',
        ),
        migrations.AlterField(
            model_name='service',
            name='mode',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_code',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
