# Generated by Django 4.2.3 on 2023-07-09 13:39

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bustimes', '0001_initial'),
        ('busstops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bustimes.timetabledatasource'),
        ),
        migrations.AddField(
            model_name='adminarea',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstops.region'),
        ),
        migrations.AddIndex(
            model_name='stoppoint',
            index=models.Index(django.db.models.functions.text.Upper('naptan_code'), name='naptan_code'),
        ),
        migrations.AddConstraint(
            model_name='stoppoint',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('atco_code'), name='atco_code'),
        ),
        migrations.AlterUniqueTogether(
            name='stopcode',
            unique_together={('code', 'source')},
        ),
        migrations.AlterUniqueTogether(
            name='servicepaymentmethod',
            unique_together={('service', 'payment_method')},
        ),
        migrations.AlterUniqueTogether(
            name='servicecode',
            unique_together={('service', 'scheme', 'code')},
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(django.db.models.functions.text.Upper('line_name'), name='line_name'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='busstops_se_search__b5811f_gin'),
        ),
        migrations.AlterUniqueTogether(
            name='operatorcode',
            unique_together={('operator', 'code', 'source')},
        ),
        migrations.AddIndex(
            model_name='operator',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='busstops_op_search__a0e028_gin'),
        ),
        migrations.AddIndex(
            model_name='locality',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='busstops_lo_search__e38767_gin'),
        ),
    ]
