# Generated by Django 4.2.7 on 2023-11-15 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operatorcode',
            unique_together={('code', 'source')},
        ),
    ]
