# Generated by Django 5.0.6 on 2024-05-22 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stopcode',
            name='source',
            field=models.ForeignKey(default=3695, limit_choices_to={'name__in': ('FlixBus', 'National coach code')}, on_delete=django.db.models.deletion.CASCADE, to='busstops.datasource'),
        ),
    ]
