# Generated by Django 3.0.7 on 2020-06-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0002_auto_20200610_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='background',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='foreground',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
