# Generated by Django 3.1.2 on 2020-10-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0002_auto_20200930_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoppoint',
            name='bearing',
            field=models.CharField(blank=True, choices=[('N', 'north ↑'), ('NE', 'north-east ↗︎'), ('E', 'east →'), ('SE', 'south-east ↘︎'), ('S', 'south ↓'), ('SW', 'south-west ↙︎'), ('W', 'west ←'), ('NW', 'north-west ↖︎')], max_length=2),
        ),
    ]
