# Generated by Django 4.0.1 on 2022-01-28 16:25

import autoslug.fields
from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0002_auto_20220114_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminarea',
            name='atco_code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='adminarea',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='district',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='locality',
            name='adjacent',
            field=models.ManyToManyField(blank=True, to='busstops.Locality'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='get_qualified_name', unique=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='siblings',
            field=models.ManyToManyField(blank=True, to='busstops.Operator'),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='naptan_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddConstraint(
            model_name='stoppoint',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('atco_code'), name='atco_code'),
        ),
    ]
