# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 19:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0002_journey_stopusageusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoppoint',
            name='osm',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
            preserve_default=False,
        ),
    ]
