# Generated by Django 5.1.1 on 2024-09-15 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0003_alter_stopcode_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='etag',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='datasource',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='busstops.datasource'),
        ),
        migrations.AddField(
            model_name='stoppoint',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='busstops.datasource'),
        ),
    ]
