# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0003_stoppoint_osm'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='stopusageusage',
            index_together=set([('stop', 'datetime'), ('journey', 'datetime')]),
        ),
    ]
