# Generated by Django 3.1.3 on 2020-11-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0003_auto_20201027_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_code',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
