# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0003_service_line_ver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminarea',
            name='name',
            field=models.CharField(db_index=True, max_length=48),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(db_index=True, max_length=48),
        ),
        migrations.AlterField(
            model_name='locality',
            name='name',
            field=models.CharField(db_index=True, max_length=48),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(db_index=True, max_length=48),
        ),
    ]
