# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0004_auto_20170308_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminarea',
            name='name',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='locality',
            name='name',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='common_name',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='stopusage',
            name='direction',
            field=models.CharField(max_length=8),
        ),
    ]
