# Generated by Django 4.1b1 on 2022-06-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("busstops", "0004_alter_locality_parent_alter_place_parent_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="operator",
            old_name="id",
            new_name="noc",
        ),
    ]
