# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0004_auto_20160322_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='current',
            field=models.NullBooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='bearing',
            field=models.CharField(blank=True, choices=[(b'N', b'north'), (b'NE', b'north east'), (b'E', b'east'), (b'SE', b'south east'), (b'S', b'south'), (b'SW', b'south west'), (b'W', b'west'), (b'NW', b'north west')], max_length=2),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='bus_stop_type',
            field=models.CharField(blank=True, choices=[(b'MKD', b'Marked (pole, shelter etc)'), (b'HAR', b'Hail and ride'), (b'CUS', b'Custom (unmarked, or only marked on road)'), (b'FLX', b'Flexible zone')], max_length=3),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='common_name',
            field=models.CharField(db_index=True, max_length=48),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='crossing',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='indicator',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='landmark',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='stop_type',
            field=models.CharField(choices=[(b'AIR', b'Airport entrance'), (b'GAT', b'Air airside area'), (b'FTD', b'Ferry terminal/dock entrance'), (b'FER', b'Ferry/dock berth area'), (b'FBT', b'Ferry berth'), (b'RSE', b'Rail station entrance'), (b'RLY', b'Rail platform access area'), (b'RPL', b'Rail platform'), (b'TMU', b'Tram/metro/underground entrance'), (b'MET', b'MET'), (b'PLT', b'Metro and underground platform access area'), (b'BCE', b'Bus/coach station entrance'), (b'BCS', b'Bus/coach bay/stand/stance within bus/coach station'), (b'BCQ', b'Bus/coach bay'), (b'BCT', b'On street bus/coach/tram stop'), (b'TXR', b'Taxi rank (head of)'), (b'STR', b'Shared taxi rank (head of)')], max_length=3),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='street',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='suburb',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='timing_status',
            field=models.CharField(blank=True, choices=[(b'PPT', b'Principal point'), (b'TIP', b'Time info point'), (b'PTP', b'Principal and time info point'), (b'OTH', b'Other bus stop')], max_length=3),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='town',
            field=models.CharField(blank=True, max_length=48),
        ),
    ]
