# Generated by Django 4.0.7 on 2022-08-18 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("busstops", "0005_rename_id_operator_noc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="inbound_description",
        ),
        migrations.RemoveField(
            model_name="service",
            name="outbound_description",
        ),
    ]
