# Generated by Django 5.1.5 on 2025-01-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0005_alter_stoppoint_atco_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecolour',
            name='use_name_as_brand',
            field=models.BooleanField(default=True),
        ),
    ]
