# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0005_auto_20160326_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoppoint',
            name='heading',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stoppoint',
            name='tfl',
            field=models.BooleanField(default=False),
        ),
    ]
