# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 21:37
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


def update_operator_slugs(apps, _):
    Operator = apps.get_model('busstops', 'Operator')
    for operator in Operator.objects.all():
        operator.slug = slugify(operator.name)
        if operator.id == 'GLOB':
            operator.slug += '-wales'
        elif operator.id == 'HCOM':
            operator.slug = 'hact'
        elif operator.id in {'OXFC', 'ACPZ'}:
            operator.slug = slugify(operator.name.split(' (', 1)[0])
        elif operator.id == 'WMSN':
            operator.slug = 'west-midlands-special-needs-ring-and-ride'
        operator.save()


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0005_auto_20170315_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=True, populate_from='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operator',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=True, populate_from='name'),
            preserve_default=False,
        ),
        migrations.RunPython(update_operator_slugs),
        migrations.AlterField(
            model_name='operator',
            name='slug',
            field=autoslug.fields.AutoSlugField(unique=True, editable=True, populate_from='name'),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=True, populate_from='description'),
            preserve_default=False,
        ),
    ]
