# Generated by Django 3.1.4 on 2020-12-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0005_auto_20201207_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
