# Generated by Django 3.1 on 2020-09-07 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0005_auto_20200811_2028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
