# Generated by Django 4.0.7 on 2022-08-24 09:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("busstops", "0006_remove_service_inbound_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
