# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-04 21:35
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0006_auto_20170403_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='name', unique=True),
        ),
    ]
