# Generated by Django 3.1.1 on 2020-09-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0006_delete_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='adjacent',
            field=models.ManyToManyField(blank=True, related_name='_locality_adjacent_+', to='busstops.Locality'),
        ),
    ]
