# Generated by Django 5.1.5 on 2025-01-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0006_servicecolour_use_name_as_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='sirisource',
            name='operators',
            field=models.ManyToManyField(blank=True, to='busstops.operator'),
        ),
        migrations.AlterField(
            model_name='servicecolour',
            name='use_name_as_brand',
            field=models.BooleanField(default=False),
        ),
    ]
