# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0006_auto_20160326_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='current',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
