# Generated by Django 3.2.3 on 2021-05-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0006_auto_20201225_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='public_use',
            field=models.BooleanField(null=True),
        ),
    ]
