# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 22:47
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0007_auto_20170404_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='description'),
        ),
    ]
