# Generated by Django 4.0.7 on 2022-09-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("busstops", "0007_alter_service_geometry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="date",
        ),
        migrations.AddField(
            model_name="operator",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="operator",
            name="qualifier_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="service",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
