# Generated by Django 3.2.7 on 2021-09-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0007_service_public_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='sha1',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='servicecolour',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
