# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 15:49
from __future__ import unicode_literals

from django.db import migrations, models


def convert_tfl_live_sources(apps, schema_editor):
    StopPoint = apps.get_model('busstops', 'StopPoint')
    LiveSource = apps.get_model('busstops', 'LiveSource')
    tfl = LiveSource.objects.create(name='TfL')
    stops = StopPoint.objects.filter(tfl=True)
    tfl.stoppoint_set.set(stops)


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0007_auto_20160328_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSource',
            fields=[
                ('name', models.CharField(max_length=4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='locality',
            old_name='adjancent',
            new_name='adjacent',
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='naptan_code',
            field=models.CharField(db_index=True, max_length=16),
        ),
        migrations.AddField(
            model_name='stoppoint',
            name='live_sources',
            field=models.ManyToManyField(to='busstops.LiveSource'),
        ),
        migrations.RunPython(convert_tfl_live_sources),
        migrations.RemoveField(
            model_name='stoppoint',
            name='tfl',
        ),
    ]
