# Generated by Django 5.2.5 on 2025-08-19 10:15

from django.db import migrations, models


def add_inbound(apps, schema_editor):
    StopUsage = apps.get_model("busstops", "StopUsage")
    StopUsage.objects.filter(direction="outbound").update(inbound=True)


def add_timing_point(apps, schema_editor):
    StopUsage = apps.get_model("busstops", "StopUsage")
    StopUsage.objects.filter(~models.Q(timing_status="PTP")).update(timing_point=True)


def add_line_names(apps, schema_editor):
    Service = apps.get_model("busstops", "Service")
    for service in Service.objects.all():
        service.stopusage_set.update(line_name=service.line_name)
        # for services with more than one line_name,
        # we need to run some code manually outside of this migration


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0008_datasource_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stopusage',
            name='inbound',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stopusage',
            name='line_name',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stopusage',
            name='timing_point',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stopusage',
            name='order',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='adminarea',
            name='atco_code',
            field=models.CharField(max_length=3, verbose_name='ATCO code'),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='atco_code',
            field=models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='ATCO code'),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='naptan_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='NaPTAN code'),
        ),
        migrations.RunPython(add_inbound, migrations.RunPython.noop),
        migrations.RunPython(add_timing_point, migrations.RunPython.noop),
        migrations.RunPython(add_line_names, migrations.RunPython.noop),
    ]
