# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def convert_stop_usage(apps, schema_editor):
    StopPoint = apps.get_model('busstops', 'StopPoint')
    StopUsage = apps.get_model('busstops', 'StopUsage')
    old_usages = StopPoint.service_set.through.objects.all()
    new_usages = (StopUsage(stop_id=old.stoppoint_id, service_id=old.service_id, order=0) for old in old_usages)
    StopUsage.objects.bulk_create(new_usages)


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0008_auto_20160416_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(db_index=True, max_length=8)),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='service',
            old_name='stops',
            new_name='stops_old',
        ),
        migrations.AddField(
            model_name='stopusage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstops.Service'),
        ),
        migrations.AddField(
            model_name='stopusage',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstops.StopPoint'),
        ),
        migrations.AddField(
            model_name='service',
            name='stops',
            field=models.ManyToManyField(editable=False, through='busstops.StopUsage', to='busstops.StopPoint'),
        ),
        migrations.RunPython(convert_stop_usage),
        migrations.RemoveField(
            model_name='service',
            name='stops_old',
        )
    ]
