# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0008_auto_20170521_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='assistance_service',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='mobility_scooter',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='wheelchair',
            field=models.NullBooleanField(),
        ),
    ]
