# Generated by Django 5.2.5 on 2025-08-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0008_datasource_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stopusage',
            name='direction',
            field=models.CharField(max_length=13),
        ),
    ]
