# Generated by Django 3.2.7 on 2021-09-14 14:51

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0008_auto_20210913_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='show_timetable',
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='naptan_code',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(django.db.models.functions.text.Upper('line_name'), name='line_name'),
        ),
        migrations.AddIndex(
            model_name='stoppoint',
            index=models.Index(django.db.models.functions.text.Upper('naptan_code'), name='naptan_code'),
        ),
    ]
