# Generated by Django 3.2.7 on 2021-09-30 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0009_auto_20210914_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stopusage',
            options={'ordering': ('-direction', 'order')},
        ),
        migrations.RemoveField(
            model_name='stoppoint',
            name='osm',
        ),
    ]
