# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0009_auto_20170620_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstops.Service')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='servicedate',
            unique_together=set([('service', 'date')]),
        ),
    ]
