# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 00:45
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0009_auto_20160416_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locality',
            name='location',
        ),
        migrations.RemoveField(
            model_name='stoparea',
            name='location',
        ),
        migrations.RemoveField(
            model_name='stoppoint',
            name='location',
        ),
        migrations.AddField(
            model_name='locality',
            name='latlong',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='stoparea',
            name='latlong',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='latlong',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
