# Generated by Django 5.2.5 on 2025-08-19 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0009_stopusage_inbound_stopusage_line_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stopusage',
            options={'ordering': ('inbound', 'order')},
        ),
        migrations.RemoveField(
            model_name='stopusage',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='stopusage',
            name='timing_status',
        ),
    ]
