# Generated by Django 4.1.1 on 2022-10-13 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bustimes", "0009_alter_routelink_unique_together"),
        ("busstops", "0009_alter_datasource_name_alter_datasource_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bustimes.timetabledatasource",
            ),
        ),
    ]
