# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0010_auto_20160417_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='address',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='operator',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='operator',
            name='phone',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='operator',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
