# Generated by Django 5.2.7 on 2025-10-17 09:16

import busstops.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0010_alter_stopusage_options_remove_stopusage_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='slug',
            field=busstops.fields.AutoSlugField(editable=True, populate_from='get_qualified_name', unique=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='slug',
            field=busstops.fields.AutoSlugField(editable=True, populate_from=str, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=busstops.fields.AutoSlugField(editable=True, populate_from=str, unique=True),
        ),
    ]
