# Generated by Django 4.1.1 on 2022-10-13 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("busstops", "0010_datasource_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatorGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=48)),
                ("name", models.CharField(max_length=100)),
                ("group_fleet_numbering", models.BooleanField(default=True)),
                ("allow_transfers", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="operator",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="busstops.operatorgroup",
            ),
        ),
    ]
