# Generated by Django 4.1.5 on 2023-01-29 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("busstops", "0011_operatorgroup_operator_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="payment_methods",
        ),
        migrations.CreateModel(
            name="ServicePaymentMethod",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accepted", models.BooleanField(default=True)),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="busstops.paymentmethod",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="busstops.service",
                    ),
                ),
            ],
            options={
                "unique_together": {("service", "payment_method")},
            },
        ),
        migrations.AddField(
            model_name="service",
            name="payment_methods",
            field=models.ManyToManyField(
                blank=True,
                through="busstops.ServicePaymentMethod",
                to="busstops.paymentmethod",
            ),
        ),
    ]
