# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 21:29
from __future__ import unicode_literals

from django.db import migrations, models


def split_line_name(apps, schema_editor):
    Service = apps.get_model('busstops', 'Service')
    services = Service.objects.filter(line_name__contains='|')
    for service in services:
        line_name_parts = service.line_name.split('|', 1)
        service.line_name = line_name_parts[0]
        service.line_brand = line_name_parts[1]
        service.save()


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0011_auto_20160417_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='line_brand',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.RunPython(split_line_name),
        migrations.AddField(
            model_name='stopusage',
            name='timing_status',
            field=models.CharField(choices=[(b'PPT', b'Principal point'), (b'TIP', b'Time info point'), (b'PTP', b'Principal and time info point'), (b'OTH', b'Other bus stop')], default='PTP', max_length=3),
            preserve_default=False,
        ),
    ]
