# Generated by Django 6.0.1 on 2026-01-25 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0011_alter_locality_slug_alter_operator_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='parent',
        ),
    ]
