# Generated by Django 6.0.3 on 2026-03-12 13:21

import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0012_remove_operator_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoppoint',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stoppoint',
            name='notes',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stoppoint',
            name='parents',
            field=models.ManyToManyField(blank=True, to='busstops.stoppoint'),
        ),
        migrations.AddField(
            model_name='stoppoint',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, null=True),
        ),
    ]
