# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0012_auto_20160522_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='service',
            name='line_brand',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='service',
            name='line_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
