# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 19:57
from __future__ import unicode_literals

import autoslug.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0012_auto_20170914_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.RunSQL("update busstops_service set slug=service_code;"),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from=str, unique=True),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='osm',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
