# Generated by Django 4.1.5 on 2023-02-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("busstops", "0012_remove_service_payment_methods_servicepaymentmethod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stoppoint",
            name="bearing",
            field=models.CharField(
                blank=True,
                choices=[
                    ("N", "north ↑"),
                    ("NE", "north-east ↗"),
                    ("E", "east →"),
                    ("SE", "south-east ↘"),
                    ("S", "south ↓"),
                    ("SW", "south-west ↙"),
                    ("W", "west ←"),
                    ("NW", "north-west ↖"),
                ],
                max_length=2,
            ),
        ),
    ]
