# Generated by Django 4.2 on 2023-04-14 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("busstops", "0013_alter_stoppoint_bearing"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datasource",
            options={"ordering": ["id"]},
        ),
    ]
