# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0013_auto_20160706_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoppoint',
            name='admin_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='busstops.AdminArea'),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='locality',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='busstops.Locality'),
        ),
    ]
