# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 20:47
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0013_auto_20171024_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from=str, unique=True),
        ),
    ]
