# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0014_auto_20160717_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoparea',
            name='stop_area_type',
            field=models.CharField(choices=[('GPBS', 'on-street pair'), ('GCLS', 'on-street cluster'), ('GAIR', 'airport building'), ('GBCS', 'bus/coach station'), ('GFTD', 'ferry terminal/dock'), ('GTMU', 'tram/metro station'), ('GRLS', 'rail station'), ('GCCH', 'coach service coverage')], max_length=4),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='bearing',
            field=models.CharField(blank=True, choices=[('N', 'north'), ('NE', 'north east'), ('E', 'east'), ('SE', 'south east'), ('S', 'south'), ('SW', 'south west'), ('W', 'west'), ('NW', 'north west')], max_length=2),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='bus_stop_type',
            field=models.CharField(blank=True, choices=[('MKD', 'Marked (pole, shelter etc)'), ('HAR', 'Hail and ride'), ('CUS', 'Custom (unmarked, or only marked on road)'), ('FLX', 'Flexible zone')], max_length=3),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='stop_type',
            field=models.CharField(choices=[('AIR', 'Airport entrance'), ('GAT', 'Air airside area'), ('FTD', 'Ferry terminal/dock entrance'), ('FER', 'Ferry/dock berth area'), ('FBT', 'Ferry berth'), ('RSE', 'Rail station entrance'), ('RLY', 'Rail platform access area'), ('RPL', 'Rail platform'), ('TMU', 'Tram/metro/underground entrance'), ('MET', 'MET'), ('PLT', 'Metro and underground platform access area'), ('BCE', 'Bus/coach station entrance'), ('BCS', 'Bus/coach bay/stand/stance within bus/coach station'), ('BCQ', 'Bus/coach bay'), ('BCT', 'On street bus/coach/tram stop'), ('TXR', 'Taxi rank (head of)'), ('STR', 'Shared taxi rank (head of)')], max_length=3),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='timing_status',
            field=models.CharField(blank=True, choices=[('PPT', 'Principal point'), ('TIP', 'Time info point'), ('PTP', 'Principal and time info point'), ('OTH', 'Other bus stop')], max_length=3),
        ),
        migrations.AlterField(
            model_name='stopusage',
            name='timing_status',
            field=models.CharField(choices=[('PPT', 'Principal point'), ('TIP', 'Time info point'), ('PTP', 'Principal and time info point'), ('OTH', 'Other bus stop')], max_length=3),
        ),
    ]
