# Generated by Django 4.2 on 2023-05-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("busstops", "0014_alter_datasource_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="mode",
            field=models.CharField(blank=True, default="bus", max_length=11),
        ),
    ]
