# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0015_auto_20171024_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminarea',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='journey',
            options={'ordering': ('datetime',)},
        ),
        migrations.AlterModelOptions(
            name='locality',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='operator',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='stoppoint',
            options={'ordering': ('common_name', 'atco_code')},
        ),
        migrations.AlterModelOptions(
            name='stopusage',
            options={'ordering': ('direction', 'order')},
        ),
        migrations.AlterModelOptions(
            name='stopusageusage',
            options={'ordering': ('datetime',)},
        ),
    ]
