# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 11:50
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0015_auto_20160805_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326),
        ),
    ]
