# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0016_service_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.District'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='parent',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.Locality'),
        ),
        migrations.AlterField(
            model_name='stoparea',
            name='parent',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.StopArea'),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='admin_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.AdminArea'),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='locality',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.Locality'),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='stop_area',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.StopArea'),
        ),
    ]
