# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 09:47
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0016_auto_20171106_1546'),
    ]

    operations = [
        migrations.RunSQL("update busstops_locality set slug=id;"),
        migrations.AlterField(
            model_name='locality',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='name', unique=True),
        ),
    ]
