# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0017_auto_20160817_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='adjacent',
            field=models.ManyToManyField(blank=True, related_name='neighbour', to='busstops.Locality'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.District'),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='live_sources',
            field=models.ManyToManyField(blank=True, to='busstops.LiveSource'),
        ),
    ]
