# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 14:35
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0017_auto_20171114_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='get_qualified_name', unique=True),
        ),
    ]
