# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 16:36
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0018_auto_20171114_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('image', models.ImageField(height_field=models.PositiveIntegerField(), upload_to='', width_field=models.PositiveIntegerField())),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstops.Service')),
            ],
        ),
        migrations.AlterField(
            model_name='locality',
            name='latlong',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ManyToManyField(blank=True, to='busstops.Image'),
        ),
        migrations.AlterUniqueTogether(
            name='servicecode',
            unique_together=set([('service', 'scheme', 'code')]),
        ),
    ]
