# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0019_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='assistance_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='low_floor',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='service',
            name='mobility_scooter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='wheelchair',
            field=models.BooleanField(default=False),
        ),
    ]
