# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 23:07
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0019_auto_20171223_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField(blank=True)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('latlong', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('parent', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.Place')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstops.DataSource')),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field='height', upload_to='', width_field='width'),
        ),
        migrations.AlterField(
            model_name='service',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='busstops.Region'),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='admin_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.AdminArea'),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='naptan_code',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='stop_type',
            field=models.CharField(blank=True, choices=[('AIR', 'Airport entrance'), ('GAT', 'Air airside area'), ('FTD', 'Ferry terminal/dock entrance'), ('FER', 'Ferry/dock berth area'), ('FBT', 'Ferry berth'), ('RSE', 'Rail station entrance'), ('RLY', 'Rail platform access area'), ('RPL', 'Rail platform'), ('TMU', 'Tram/metro/underground entrance'), ('MET', 'MET'), ('PLT', 'Metro and underground platform access area'), ('BCE', 'Bus/coach station entrance'), ('BCS', 'Bus/coach bay/stand/stance within bus/coach station'), ('BCQ', 'Bus/coach bay'), ('BCT', 'On street bus/coach/tram stop'), ('TXR', 'Taxi rank (head of)'), ('STR', 'Shared taxi rank (head of)')], max_length=3),
        ),
        migrations.AddField(
            model_name='stoppoint',
            name='places',
            field=models.ManyToManyField(blank=True, to='busstops.Place'),
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together=set([('source', 'code')]),
        ),
    ]
