# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0020_auto_20171228_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=100)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstops.Operator')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstops.DataSource')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='operatorcode',
            unique_together=set([('code', 'source')]),
        ),
    ]
