# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 16:07
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0021_auto_20180109_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
