# Generated by Django 2.0.4 on 2018-04-19 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0022_place_polygon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(max_length=255)),
                ('from_email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('spam_score', models.PositiveIntegerField()),
                ('ip_address', models.GenericIPAddressField()),
                ('referrer', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20)),
                ('variation_number', models.PositiveIntegerField()),
                ('service_number', models.CharField(max_length=20)),
                ('traffic_area', models.CharField(max_length=1)),
                ('licence_number', models.CharField(max_length=20)),
                ('discs', models.PositiveIntegerField()),
                ('authorised_discs', models.PositiveIntegerField()),
                ('granted_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('start_point', models.CharField(max_length=255)),
                ('finish_point', models.CharField(max_length=255)),
                ('via', models.CharField(blank=True, max_length=255)),
                ('effective_date', models.DateField()),
                ('date_received', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('service_type_other_details', models.CharField(max_length=255)),
                ('licence_status', models.CharField(max_length=255)),
                ('registration_status', models.CharField(max_length=255)),
                ('publication_text', models.TextField()),
                ('service_type_description', models.CharField(max_length=255)),
                ('short_notice', models.CharField(max_length=255)),
                ('subsidies_description', models.CharField(max_length=255)),
                ('subsidies_details', models.CharField(max_length=255)),
                ('authoritiy_description', models.CharField(max_length=255)),
                ('traffic_area_office_covered_by_area', models.CharField(max_length=100)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.OperatorCode')),
            ],
        ),
        migrations.AddField(
            model_name='servicedate',
            name='end',
            field=models.DateTimeField(null=True),
        ),
    ]
