# Generated by Django 2.0.4 on 2018-04-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0023_auto_20180420_0755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'ordering': ('-variation_number',)},
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_status',
            field=models.CharField(db_index=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='licence_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together={('registration', 'variation_number')},
        ),
    ]
