# Generated by Django 2.0.5 on 2018-05-22 11:28

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0024_auto_20180429_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.Operator')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstops.DataSource')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('datetime', models.DateTimeField()),
                ('latlong', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'ordering': ('datetime',),
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('service_code',)},
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.Service'),
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstops.DataSource'),
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.Vehicle'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('code', 'source')},
        ),
    ]
