# Generated by Django 2.0.4 on 2018-06-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0025_auto_20180522_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.RemoveField(
            model_name='stoppoint',
            name='live_sources',
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='bearing',
            field=models.CharField(blank=True, choices=[('N', 'north'), ('NE', 'north-east'), ('E', 'east'), ('SE', 'south-east'), ('S', 'south'), ('SW', 'south-west'), ('W', 'west'), ('NW', 'north-west')], max_length=2),
        ),
        migrations.AlterIndexTogether(
            name='vehiclelocation',
            index_together={('source', 'datetime')},
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='LiveSource',
        ),
    ]
