# Generated by Django 2.0.6 on 2018-06-10 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0027_auto_20180609_2250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclelocation',
            options={'ordering': ('id',)},
        ),
        migrations.AlterIndexTogether(
            name='vehiclelocation',
            index_together=set(),
        ),
    ]
