# Generated by Django 2.0.7 on 2018-07-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0029_auto_20180710_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ('code',)},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fleet_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='reg',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterIndexTogether(
            name='vehiclelocation',
            index_together={('service', 'datetime'), ('vehicle', 'datetime')},
        ),
    ]
