# Generated by Django 2.0.7 on 2018-07-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0030_auto_20180724_1453'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='vehiclelocation',
            index_together={('source', 'current'), ('service', 'datetime'), ('vehicle', 'current'), ('vehicle', 'datetime'), ('service', 'current')},
        ),
    ]
