# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0030_auto_20151128_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='line_name',
            field=models.CharField(max_length=64),
        ),
    ]
