# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0031_auto_20151220_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='current',
            field=models.NullBooleanField(default=True),
        ),
    ]
