# Generated by Django 2.1 on 2018-08-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0031_auto_20180724_1613'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('code', 'operator'), ('code', 'source')},
        ),
    ]
