# Generated by Django 2.1 on 2018-08-29 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0032_auto_20180827_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('code', 'operator')},
        ),
    ]
