# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0032_auto_20160116_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='mode',
            field=models.CharField(max_length=11),
        ),
    ]
