# Generated by Django 2.1.1 on 2018-09-24 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0033_auto_20180829_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIRISource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('requestor_ref', models.CharField(blank=True, max_length=255)),
                ('admin_areas', models.ManyToManyField(blank=True, to='busstops.AdminArea')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='latest_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_vehicle', to='busstops.VehicleLocation'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
