# Generated by Django 2.1.4 on 2018-12-23 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0035_auto_20181223_1524'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='latest_location',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='source',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_type',
        ),
        migrations.AlterIndexTogether(
            name='vehiclelocation',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='vehiclelocation',
            name='service',
        ),
        migrations.RemoveField(
            model_name='vehiclelocation',
            name='source',
        ),
        migrations.RemoveField(
            model_name='vehiclelocation',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.DeleteModel(
            name='VehicleLocation',
        ),
        migrations.DeleteModel(
            name='VehicleType',
        ),
    ]
