# Generated by Django 2.1.5 on 2019-01-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0036_auto_20181223_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
