# Generated by Django 2.1.7 on 2019-04-01 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0038_auto_20190224_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how', models.CharField(max_length=10)),
                ('from_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_from', to='busstops.Service')),
                ('to_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_to', to='busstops.Service')),
            ],
        ),
        migrations.RemoveField(
            model_name='registration',
            name='operator',
        ),
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='variation',
            name='registration',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
        migrations.AddField(
            model_name='operator',
            name='payment_methods',
            field=models.ManyToManyField(blank=True, to='busstops.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='service',
            name='payment_methods',
            field=models.ManyToManyField(blank=True, to='busstops.PaymentMethod'),
        ),
    ]
