# Generated by Django 2.2.1 on 2019-05-07 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0039_auto_20190401_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.DataSource'),
        ),
        migrations.AddField(
            model_name='service',
            name='tracking',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='locality_centre',
            field=models.NullBooleanField(),
        ),
    ]
