# Generated by Django 2.2.1 on 2019-05-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0041_stopcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='aka',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='operatorcode',
            unique_together={('operator', 'code', 'source')},
        ),
    ]
