# Generated by Django 2.2.2 on 2019-07-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vosa', '0001_initial'),
        ('busstops', '0042_auto_20190529_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='licences',
            field=models.ManyToManyField(blank=True, to='vosa.Licence'),
        ),
    ]
