# Generated by Django 2.2.3 on 2019-08-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0043_operator_licences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelink',
            name='how',
            field=models.CharField(choices=[('parallel', 'Combine timetables'), ('also', 'Just list')], max_length=10),
        ),
    ]
