# Generated by Django 2.2.6 on 2019-10-19 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0046_auto_20191001_1255'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='stopusageusage',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='stopusageusage',
            name='journey',
        ),
        migrations.RemoveField(
            model_name='stopusageusage',
            name='stop',
        ),
        migrations.DeleteModel(
            name='Journey',
        ),
        migrations.DeleteModel(
            name='StopUsageUsage',
        ),
    ]
