# Generated by Django 2.2.8 on 2019-12-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0047_auto_20191020_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoppoint',
            name='bearing',
            field=models.CharField(blank=True, choices=[('N', 'north ↑'), ('NE', 'north-east ↗'), ('E', 'east →'), ('SE', 'south-east ↘'), ('S', 'south ↓'), ('SW', 'south-west ↙'), ('W', 'west ←'), ('NW', 'north-west ↖')], max_length=2),
        ),
    ]
