# Generated by Django 2.2.9 on 2020-01-25 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0048_auto_20191220_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='line_ver',
        ),
        migrations.RemoveField(
            model_name='service',
            name='net',
        ),
    ]
