# Generated by Django 2.2.10 on 2020-02-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0049_auto_20200125_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='operators',
            field=models.ManyToManyField(blank=True, limit_choices_to={'service__current': True}, to='busstops.Operator'),
        ),
    ]
