# Generated by Django 2.2.11 on 2020-03-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0050_auto_20200229_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='operators',
            field=models.ManyToManyField(blank=True, to='busstops.Operator'),
        ),
    ]
