# Generated by Django 2.2.12 on 2020-04-16 11:32

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0051_auto_20200322_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['service_code']},
        ),
        migrations.AddIndex(
            model_name='locality',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='busstops_lo_search__e38767_gin'),
        ),
        migrations.AddIndex(
            model_name='operator',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='busstops_op_search__a0e028_gin'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='busstops_se_search__b5811f_gin'),
        ),
    ]
