# Generated by Django 5.0.1 on 2024-01-07 12:14

import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('disruptions', '0001_initial'), ('disruptions', '0002_rename_situation_current_publication_window_disruptions_current_cfec06_idx_and_more')]

    initial = True

    dependencies = [
        ('busstops', '0001_initial'),
        ('busstops', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation_number', models.CharField(blank=True, max_length=36)),
                ('reason', models.CharField(blank=True, max_length=25)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True)),
                ('data', models.TextField(blank=True)),
                ('created', models.DateTimeField()),
                ('publication_window', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('current', models.BooleanField(default=True)),
                ('source', models.ForeignKey(limit_choices_to={'name__in': ('Ito World', 'TfE', 'TfL', 'Transport for the North', 'Transport for West Midlands', 'bustimes.org')}, on_delete=django.db.models.deletion.CASCADE, to='busstops.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='ValidityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disruptions.situation')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disruptions.situation')),
            ],
        ),
        migrations.CreateModel(
            name='Consequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('data', models.TextField(blank=True)),
                ('operators', models.ManyToManyField(blank=True, to='busstops.operator')),
                ('services', models.ManyToManyField(blank=True, to='busstops.service')),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disruptions.situation')),
                ('stops', models.ManyToManyField(blank=True, to='busstops.stoppoint')),
            ],
        ),
        migrations.AddIndex(
            model_name='situation',
            index=models.Index(fields=('current', 'publication_window'), name="disruptions_current_cfec06_idx"),
        ),
        migrations.AddField(
            model_name='situation',
            name='participant_ref',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='situation',
            name='source',
            field=models.ForeignKey(limit_choices_to={'name__in': ('bustimes.org', 'Bus Open Data Service', 'Ito World', 'TfL', 'Transport for the North')}, on_delete=django.db.models.deletion.CASCADE, to='busstops.datasource'),
        ),
        migrations.AddIndex(
            model_name='situation',
            index=models.Index(fields=['source', 'situation_number'], name='disruptions_source__e0ddcb_idx'),
        ),
    ]
