# Generated by Django 3.0.6 on 2020-05-12 11:37

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('busstops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation_number', models.CharField(max_length=36)),
                ('summary', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=25)),
                ('text', models.TextField()),
                ('data', models.TextField()),
                ('created', models.DateTimeField()),
                ('publication_window', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('validity_period', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('operator', models.ManyToManyField(to='busstops.Operator')),
                ('services', models.ManyToManyField(to='busstops.Service')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstops.DataSource')),
                ('stops', models.ManyToManyField(to='busstops.StopPoint')),
            ],
            options={
                'unique_together': {('source', 'situation_number')},
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disruptions.Situation')),
            ],
        ),
    ]
