# Generated by Django 4.2.3 on 2023-07-09 13:39

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('busstops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation_number', models.CharField(blank=True, max_length=36)),
                ('reason', models.CharField(blank=True, max_length=25)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True)),
                ('data', models.TextField(blank=True)),
                ('created', models.DateTimeField()),
                ('publication_window', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('current', models.BooleanField(default=True)),
                ('source', models.ForeignKey(limit_choices_to={'name__in': ('Ito World', 'TfE', 'TfL', 'Transport for the North', 'Transport for West Midlands', 'bustimes.org')}, on_delete=django.db.models.deletion.CASCADE, to='busstops.datasource')),
            ],
            options={
                'unique_together': {('source', 'situation_number')},
                'index_together': {('current', 'publication_window')},
            },
        ),
        migrations.CreateModel(
            name='ValidityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disruptions.situation')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disruptions.situation')),
            ],
        ),
        migrations.CreateModel(
            name='Consequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('data', models.TextField(blank=True)),
                ('operators', models.ManyToManyField(blank=True, to='busstops.operator')),
                ('services', models.ManyToManyField(blank=True, to='busstops.service')),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disruptions.situation')),
                ('stops', models.ManyToManyField(blank=True, to='busstops.stoppoint')),
            ],
        ),
    ]
