# Generated by Django 3.1.1 on 2020-09-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0001_initial'),
        ('disruptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consequence',
            name='data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consequence',
            name='operators',
            field=models.ManyToManyField(blank=True, to='busstops.Operator'),
        ),
        migrations.AlterField(
            model_name='consequence',
            name='services',
            field=models.ManyToManyField(blank=True, to='busstops.Service'),
        ),
        migrations.AlterField(
            model_name='consequence',
            name='stops',
            field=models.ManyToManyField(blank=True, to='busstops.StopPoint'),
        ),
        migrations.AlterField(
            model_name='consequence',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='situation',
            name='data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='situation',
            name='reason',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='situation',
            name='situation_number',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='situation',
            name='summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='situation',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
