# Generated by Django 3.1 on 2020-08-11 19:28

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0005_auto_20200811_2028'),
        ('disruptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopSuspension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', django.contrib.postgres.fields.ranges.DateTimeRangeField(null=True)),
                ('text', models.TextField(blank=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='busstops.service')),
                ('stops', models.ManyToManyField(to='busstops.StopPoint')),
            ],
        ),
    ]
