# Generated by Django 4.2.6 on 2023-10-09 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0002_initial'),
        ('disruptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='situation',
            new_name='disruptions_current_cfec06_idx',
            old_fields=('current', 'publication_window'),
        ),
        migrations.AlterUniqueTogether(
            name='situation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='situation',
            name='participant_ref',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='situation',
            name='source',
            field=models.ForeignKey(limit_choices_to={'name__in': ('bustimes.org', 'Bus Open Data Service', 'Ito World', 'TfL', 'Transport for the North')}, on_delete=django.db.models.deletion.CASCADE, to='busstops.datasource'),
        ),
        migrations.AddIndex(
            model_name='situation',
            index=models.Index(fields=['source', 'situation_number'], name='disruptions_source__e0ddcb_idx'),
        ),
    ]
