# Generated by Django 3.1 on 2020-08-25 16:30

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disruptions', '0002_stopsuspension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stopsuspension',
            name='dates',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, null=True),
        ),
    ]
