# Generated by Django 3.1.3 on 2020-12-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disruptions', '0002_auto_20200930_1131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StopSuspension',
        ),
    ]
