# Generated by Django 5.1.8 on 2025-04-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disruptions', '0003_alter_situation_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='situation',
            name='show_summary',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='situation',
            name='summary',
            field=models.CharField(blank=True, help_text='(title)', max_length=255),
        ),
    ]
