# Generated by Django 5.2.1 on 2025-05-21 10:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disruptions', '0004_situation_show_summary_alter_situation_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='situation',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='situation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='situation',
            name='modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
