# Generated by Django 4.0.2 on 2022-02-14 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0003_alter_adminarea_atco_code_alter_adminarea_id_and_more'),
        ('disruptions', '0004_auto_20210115_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situation',
            name='source',
            field=models.ForeignKey(limit_choices_to={'name__in': ('Transport for the North', 'Transport for West Midlands', 'bustimes.org')}, on_delete=django.db.models.deletion.CASCADE, to='busstops.datasource'),
        ),
    ]
