# Generated by Django 4.0.3 on 2022-04-13 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0004_alter_locality_parent_alter_place_parent_and_more'),
        ('disruptions', '0005_alter_situation_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situation',
            name='source',
            field=models.ForeignKey(limit_choices_to={'name__in': ('Ito World', 'Transport for the North', 'Transport for West Midlands', 'bustimes.org')}, on_delete=django.db.models.deletion.CASCADE, to='busstops.datasource'),
        ),
    ]
