# Generated by Django 5.2.3 on 2025-06-19 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0007_version_route_version'),
        ('disruptions', '0005_rename_created_situation_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectedJourney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_departure_time', models.DateTimeField(blank=True, null=True)),
                ('condition', models.CharField()),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disruptions.situation')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bustimes.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('condition', models.CharField()),
                ('order', models.PositiveSmallIntegerField()),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disruptions.affectedjourney')),
                ('stop_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bustimes.stoptime')),
            ],
        ),
    ]
