# Generated by Django 5.2.4 on 2025-07-31 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0008_datasource_description'),
        ('disruptions', '0006_affectedjourney_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situation',
            name='source',
            field=models.ForeignKey(default=236, limit_choices_to={'name__in': ('bustimes.org', 'TfL', 'TfL disruptions', 'TfL statuses', 'BODS disruptions', 'BODS cancellations', 'Bus Open Data')}, on_delete=django.db.models.deletion.CASCADE, to='busstops.datasource'),
        ),
    ]
