# Generated by Django 4.2.3 on 2023-07-09 13:39

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('busstops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('operators', models.ManyToManyField(blank=True, to='busstops.operator')),
            ],
        ),
        migrations.CreateModel(
            name='FareTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FareZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fares.dataset')),
                ('stops', models.ManyToManyField(blank=True, to='busstops.stoppoint')),
            ],
        ),
        migrations.CreateModel(
            name='PreassignedFareProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=140)),
                ('name', models.CharField(blank=True, max_length=140)),
                ('charging_moment', models.CharField(blank=True, max_length=25)),
                ('tariff_basis', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOfferPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('cash', models.BooleanField(default=False)),
                ('contactless', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TimeInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('proof_required', models.CharField(blank=True, max_length=255)),
                ('discount_basis', models.CharField(blank=True, max_length=255)),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('trip_type', models.CharField(blank=True, max_length=255)),
                ('valid_between', django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, null=True)),
                ('type_of_tariff', models.CharField(blank=True, choices=[('point_to_point', 'Point to point'), ('zonal', 'Zonal')], max_length=19)),
                ('access_zones', models.ManyToManyField(blank=True, to='fares.farezone')),
                ('operators', models.ManyToManyField(blank=True, to='busstops.operator')),
                ('services', models.ManyToManyField(blank=True, to='busstops.service')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fares.dataset')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fares.userprofile')),
            ],
            options={
                'unique_together': {('source', 'filename', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fares.faretable')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sales_offer_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fares.salesofferpackage')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fares.tariff')),
                ('time_interval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fares.timeinterval')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fares.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='faretable',
            name='preassigned_fare_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fares.preassignedfareproduct'),
        ),
        migrations.AddField(
            model_name='faretable',
            name='sales_offer_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fares.salesofferpackage'),
        ),
        migrations.AddField(
            model_name='faretable',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fares.tariff'),
        ),
        migrations.AddField(
            model_name='faretable',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fares.userprofile'),
        ),
        migrations.CreateModel(
            name='DistanceMatrixElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('end_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending', to='fares.farezone')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fares.price')),
                ('start_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting', to='fares.farezone')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fares.tariff')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fares.faretable')),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fares.column')),
                ('distance_matrix_element', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fares.distancematrixelement')),
                ('price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fares.price')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fares.row')),
            ],
        ),
    ]
