# Generated by Django 6.0.3 on 2026-03-12 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0012_remove_operator_parent'),
        ('fares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_id', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('currency', models.CharField(max_length=3)),
                ('payment_method', models.PositiveSmallIntegerField()),
                ('transfers', models.PositiveSmallIntegerField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstops.datasource')),
            ],
            options={
                'unique_together': {('source', 'fare_id')},
            },
        ),
        migrations.CreateModel(
            name='FareRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='destination_rules', to='busstops.stoppoint')),
                ('fare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fares.fare')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='origin_rules', to='busstops.stoppoint')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='busstops.service')),
            ],
        ),
    ]
