# Generated by Django 3.1.4 on 2020-12-22 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faretable',
            name='sales_offer_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fares.salesofferpackage'),
        ),
        migrations.AlterField(
            model_name='faretable',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fares.tariff'),
        ),
        migrations.AlterField(
            model_name='faretable',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fares.userprofile'),
        ),
    ]
