# Generated by Django 3.2.5 on 2021-08-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0003_auto_20210602_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='access_zones',
            field=models.ManyToManyField(blank=True, to='fares.FareZone'),
        ),
    ]
