# Generated by Django 4.0.2 on 2022-03-20 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0004_alter_tariff_access_zones'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreassignedFareProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=140)),
                ('name', models.CharField(blank=True, max_length=140)),
                ('charging_moment', models.CharField(blank=True, max_length=25)),
                ('tariff_basis', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='salesofferpackage',
            name='cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesofferpackage',
            name='contactless',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faretable',
            name='preassigned_fare_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fares.preassignedfareproduct'),
        ),
    ]
