# Generated by Django 4.0.2 on 2022-03-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0005_preassignedfareproduct_salesofferpackage_cash_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tariff',
            unique_together={('source', 'filename', 'code')},
        ),
    ]
