# Generated by Django 4.1.5 on 2023-02-03 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fares", "0006_alter_tariff_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="farezone",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fares.dataset",
            ),
        ),
        migrations.AlterField(
            model_name="faretable",
            name="tariff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="fares.tariff"
            ),
        ),
    ]
