# Generated by Django 4.0.2 on 2022-02-14 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0003_alter_adminarea_atco_code_alter_adminarea_id_and_more'),
        ('accounts', '0001_squashed_0004_auto_20201209_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.BooleanField(default=False)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstops.operator')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='operators',
            field=models.ManyToManyField(blank=True, through='accounts.OperatorUser', to='busstops.Operator'),
        ),
        migrations.AddField(
            model_name='operatoruser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
