# Generated by Django 4.0.7 on 2022-08-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_operatoruser_user_operators_operatoruser_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
