# Generated by Django 5.2.6 on 2025-09-15 15:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('busstops', '0010_alter_stopusage_options_remove_stopusage_direction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('expires_at', models.DateTimeField()),
                ('operators', models.ManyToManyField(blank=True, to='busstops.operator')),
            ],
        ),
    ]
