# Generated by Django 4.2.2 on 2023-06-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_ip_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
