# Generated by Django 6.0.7 on 2026-07-23 18:36

import bustimes.fields
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseVersion',
            fields=[
                ('version', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.PositiveIntegerField()),
                ('operator_code', models.CharField(max_length=10)),
                ('block_no', models.PositiveIntegerField()),
                ('running_no', models.PositiveSmallIntegerField()),
                ('base_version', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='tfl.baseversion')),
            ],
            options={
                'indexes': [models.Index(fields=['base_version', 'idx'], name='tfl_block_base_ve_f26d8d_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlockCalendarDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_idx', models.PositiveIntegerField()),
                ('calendar_day', models.DateField()),
                ('runs', models.BooleanField()),
                ('base_version', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='tfl.baseversion')),
            ],
            options={
                'indexes': [models.Index(fields=['base_version', 'block_idx'], name='tfl_blockca_base_ve_0feb9f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.PositiveIntegerField()),
                ('long_name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
                ('base_version', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='tfl.baseversion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('base_version', 'idx'), name='tfl_destination_unique')],
            },
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('operator_code', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('base_version', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='tfl.baseversion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('base_version', 'number'), name='tfl_garage_unique')],
            },
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.PositiveIntegerField()),
                ('pattern_idx', models.PositiveIntegerField()),
                ('block_idx', models.PositiveIntegerField()),
                ('trip_no_lbsl', models.PositiveSmallIntegerField()),
                ('type', models.PositiveSmallIntegerField()),
                ('start_time', bustimes.fields.SecondsField()),
                ('base_version', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='tfl.baseversion')),
            ],
            options={
                'indexes': [models.Index(fields=['base_version', 'idx'], name='tfl_journey_base_ve_2e5c12_idx'), models.Index(fields=['base_version', 'block_idx'], name='tfl_journey_base_ve_b8a712_idx'), models.Index(fields=['base_version', 'pattern_idx'], name='tfl_journey_base_ve_7d8dd1_idx')],
            },
        ),
        migrations.CreateModel(
            name='JourneyDriveTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_idx', models.PositiveIntegerField()),
                ('stop_in_pattern_from_idx', models.PositiveIntegerField()),
                ('stop_in_pattern_to_idx', models.PositiveIntegerField()),
                ('drive_time', bustimes.fields.SecondsField()),
                ('base_version', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='tfl.baseversion')),
            ],
            options={
                'indexes': [models.Index(fields=['base_version', 'journey_idx'], name='tfl_journey_base_ve_cb5150_idx')],
            },
        ),
        migrations.CreateModel(
            name='JourneyWaitTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_idx', models.PositiveIntegerField()),
                ('stop_in_pattern_idx', models.PositiveIntegerField()),
                ('wait_time', bustimes.fields.SecondsField()),
                ('base_version', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='tfl.baseversion')),
            ],
            options={
                'indexes': [models.Index(fields=['base_version', 'journey_idx'], name='tfl_journey_base_ve_6df785_idx')],
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_line_no', models.CharField(max_length=10)),
                ('service_line_no', models.CharField(max_length=10)),
                ('logical_line_no', models.PositiveIntegerField()),
                ('base_version', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='tfl.baseversion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('base_version', 'contract_line_no'), name='tfl_line_unique')],
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('agency', models.CharField(blank=True, max_length=100)),
                ('base_version', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='tfl.baseversion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('base_version', 'code'), name='tfl_operator_unique')],
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.PositiveIntegerField()),
                ('contract_line_no', models.CharField(max_length=10)),
                ('direction', models.PositiveSmallIntegerField()),
                ('type', models.PositiveSmallIntegerField()),
                ('base_version', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='tfl.baseversion')),
            ],
            options={
                'indexes': [models.Index(fields=['base_version', 'idx'], name='tfl_pattern_base_ve_97c20f_idx'), models.Index(fields=['base_version', 'contract_line_no'], name='tfl_pattern_base_ve_051fec_idx')],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.PositiveIntegerField()),
                ('naptan_code', models.CharField(blank=True, db_index=True, max_length=20)),
                ('stop_code_lbsl', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('latlong', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('point_letter', models.CharField(blank=True, max_length=5)),
                ('sms_code', models.CharField(blank=True, max_length=10)),
                ('stop_area', models.CharField(blank=True, max_length=20)),
                ('borough_code', models.CharField(blank=True, max_length=10)),
                ('heading', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stop_type', models.CharField(blank=True, max_length=10)),
                ('street_name', models.CharField(blank=True, max_length=100)),
                ('post_code', models.CharField(blank=True, max_length=10)),
                ('towards', models.CharField(blank=True, max_length=100)),
                ('base_version', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='tfl.baseversion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('base_version', 'idx'), name='tfl_stop_unique')],
            },
        ),
        migrations.CreateModel(
            name='StopInPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.PositiveIntegerField()),
                ('pattern_idx', models.PositiveIntegerField()),
                ('destination_idx', models.PositiveIntegerField(blank=True, null=True)),
                ('stop_idx', models.PositiveIntegerField()),
                ('sequence_no', models.PositiveSmallIntegerField()),
                ('timing_point_code', models.CharField(blank=True, max_length=10)),
                ('base_version', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='tfl.baseversion')),
            ],
            options={
                'indexes': [models.Index(fields=['base_version', 'idx'], name='tfl_stopinp_base_ve_573a4f_idx'), models.Index(fields=['base_version', 'pattern_idx'], name='tfl_stopinp_base_ve_b92039_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.PositiveIntegerField()),
                ('registration_number', models.CharField(blank=True, max_length=20)),
                ('bonnet_no', models.CharField(blank=True, max_length=20)),
                ('operator_agency', models.CharField(blank=True, max_length=100)),
                ('base_version', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='tfl.baseversion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('base_version', 'vehicle_id'), name='tfl_vehicle_unique')],
            },
        ),
    ]
