# Generated by Django 3.0.7 on 2020-06-03 23:38

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('busstops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon', models.BooleanField()),
                ('tue', models.BooleanField()),
                ('wed', models.BooleanField()),
                ('thu', models.BooleanField()),
                ('fri', models.BooleanField()),
                ('sat', models.BooleanField()),
                ('sun', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('dates', django.contrib.postgres.fields.ranges.DateRangeField(null=True)),
            ],
            options={
                'index_together': {('start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('line_brand', models.CharField(blank=True, max_length=255)),
                ('line_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('dates', django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstops.Service')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstops.DataSource')),
            ],
            options={
                'unique_together': {('source', 'code')},
                'index_together': {('start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound', models.BooleanField(default=False)),
                ('journey_pattern', models.CharField(blank=True, max_length=255)),
                ('sequence', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start', models.DurationField()),
                ('end', models.DurationField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bustimes.Calendar')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstops.StopPoint')),
                ('notes', models.ManyToManyField(blank=True, to='bustimes.Note')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bustimes.Route')),
            ],
            options={
                'index_together': {('route', 'start', 'end')},
            },
        ),
        migrations.CreateModel(
            name='CalendarDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('dates', django.contrib.postgres.fields.ranges.DateRangeField(null=True)),
                ('operation', models.BooleanField(db_index=True)),
                ('special', models.BooleanField(db_index=True, default=False)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bustimes.Calendar')),
            ],
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stop_code', models.CharField(max_length=255)),
                ('arrival', models.DurationField()),
                ('departure', models.DurationField()),
                ('sequence', models.PositiveSmallIntegerField()),
                ('timing_status', models.CharField(blank=True, max_length=3)),
                ('activity', models.CharField(blank=True, max_length=16)),
                ('stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.StopPoint')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bustimes.Trip')),
            ],
            options={
                'ordering': ('sequence',),
                'index_together': {('stop', 'departure')},
            },
        ),
    ]
