# Generated by Django 3.2.7 on 2021-09-30 19:51

import bustimes.fields
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('bustimes', '0001_initial'), ('bustimes', '0002_auto_20200930_1131'), ('bustimes', '0003_auto_20201027_1338'), ('bustimes', '0004_auto_20201127_1220'), ('bustimes', '0005_auto_20201224_2350'), ('bustimes', '0006_auto_20210115_1956'), ('bustimes', '0007_auto_20210514_1616'), ('bustimes', '0008_auto_20210722_1606'), ('bustimes', '0009_auto_20210817_2045'), ('bustimes', '0010_alter_stoptime_options'), ('bustimes', '0011_routelink'), ('bustimes', '0012_alter_route_revision_number')]

    initial = True

    dependencies = [
        ('busstops', '0006_auto_20201225_0004'),
        ('busstops', '0001_initial'),
        ('busstops', '0010_auto_20210930_1810'),
        ('vosa', '0002_auto_20201121_0959'),
        ('busstops', '0007_service_public_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon', models.BooleanField()),
                ('tue', models.BooleanField()),
                ('wed', models.BooleanField()),
                ('thu', models.BooleanField()),
                ('fri', models.BooleanField()),
                ('sat', models.BooleanField()),
                ('sun', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('dates', django.contrib.postgres.fields.ranges.DateRangeField(null=True)),
                ('summary', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'index_together': {('start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('line_brand', models.CharField(blank=True, max_length=255)),
                ('line_name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('dates', django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstops.service')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstops.datasource')),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('origin', models.CharField(blank=True, max_length=255)),
                ('via', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'unique_together': {('source', 'code')},
                'index_together': {('start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound', models.BooleanField(default=False)),
                ('journey_pattern', models.CharField(blank=True, max_length=255)),
                ('sequence', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start', models.DurationField()),
                ('end', models.DurationField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bustimes.calendar')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.stoppoint')),
                ('notes', models.ManyToManyField(blank=True, to='bustimes.Note')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bustimes.route')),
                ('block', models.CharField(blank=True, db_index=True, max_length=255)),
                ('ticket_machine_code', models.CharField(blank=True, db_index=True, max_length=255)),
            ],
            options={
                'index_together': {('route', 'start', 'end')},
            },
        ),
        migrations.CreateModel(
            name='BankHoliday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('dates', django.contrib.postgres.fields.ranges.DateRangeField(null=True)),
                ('operation', models.BooleanField(db_index=True)),
                ('special', models.BooleanField(db_index=True, default=False)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bustimes.calendar')),
                ('summary', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BankHolidayDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('scotland', models.BooleanField(null=True)),
                ('bank_holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bustimes.bankholiday')),
            ],
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stop_code', models.CharField(blank=True, max_length=255)),
                ('arrival', models.DurationField()),
                ('departure', models.DurationField()),
                ('sequence', models.PositiveSmallIntegerField()),
                ('timing_status', models.CharField(blank=True, max_length=3)),
                ('activity', models.CharField(blank=True, max_length=16)),
                ('stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.stoppoint')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bustimes.trip')),
                ('pick_up', models.BooleanField(default=True)),
                ('set_down', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('sequence',),
                'index_together': {('stop', 'departure')},
            },
        ),
        migrations.RunSQL(
            sql='\n                ALTER TABLE "bustimes_stoptime" ALTER COLUMN "arrival" TYPE integer USING EXTRACT(EPOCH FROM "arrival"), ALTER COLUMN "arrival" DROP NOT NULL;\n                ALTER TABLE "bustimes_stoptime" ALTER COLUMN "departure" TYPE integer USING EXTRACT(EPOCH FROM "departure"), ALTER COLUMN "departure" DROP NOT NULL;\n                ALTER TABLE "bustimes_trip" ALTER COLUMN "end" TYPE integer USING EXTRACT(EPOCH FROM "end");\n                ALTER TABLE "bustimes_trip" ALTER COLUMN "start" TYPE integer USING EXTRACT(EPOCH FROM "start");\n            ',
            state_operations=[migrations.AlterField(
                model_name='stoptime',
                name='arrival',
                field=bustimes.fields.SecondsField(blank=True, null=True),
            ), migrations.AlterField(
                model_name='stoptime',
                name='departure',
                field=bustimes.fields.SecondsField(blank=True, null=True),
            ), migrations.AlterField(
                model_name='trip',
                name='end',
                field=bustimes.fields.SecondsField(),
            ), migrations.AlterField(
                model_name='trip',
                name='start',
                field=bustimes.fields.SecondsField(),
            )],
        ),
        migrations.AddField(
            model_name='route',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vosa.registration'),
        ),
        migrations.AddField(
            model_name='route',
            name='service_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='route',
            name='line_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='route',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, editable=False, null=True, srid=4326),
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.operator')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='garage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bustimes.garage'),
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='dates',
        ),
        migrations.RemoveField(
            model_name='calendardate',
            name='dates',
        ),
        migrations.RemoveField(
            model_name='route',
            name='dates',
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bustimes.vehicletype'),
        ),
        migrations.CreateModel(
            name='CalendarBankHoliday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.BooleanField()),
                ('bank_holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bustimes.bankholiday')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bustimes.calendar')),
            ],
            options={
                'unique_together': {('bank_holiday', 'calendar')},
            },
        ),
        migrations.AddField(
            model_name='calendar',
            name='bank_holidays',
            field=models.ManyToManyField(through='bustimes.CalendarBankHoliday', to='bustimes.BankHoliday'),
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='stoptime',
            name='activity',
        ),
        migrations.AddField(
            model_name='trip',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.operator'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bustimes.calendar'),
        ),
        migrations.RemoveField(
            model_name='trip',
            name='block',
        ),
        migrations.AddField(
            model_name='trip',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bustimes.block'),
        ),
        migrations.AlterField(
            model_name='bankholiday',
            name='id',
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stoptime',
            name='sequence',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bustimes.calendar'),
        ),
        migrations.AlterModelOptions(
            name='stoptime',
            options={'ordering': ('id',)},
        ),
        migrations.CreateModel(
            name='RouteLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_metres', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('override', models.BooleanField(default=False)),
                ('from_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_from', to='busstops.stoppoint')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstops.service')),
                ('to_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_to', to='busstops.stoppoint')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='revision_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
