# Generated by Django 4.2.3 on 2023-07-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoptime',
            name='notes',
            field=models.ManyToManyField(blank=True, to='bustimes.note'),
        ),
    ]
