# Generated by Django 3.1.1 on 2020-09-30 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankHoliday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='calendar',
            name='summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='calendardate',
            name='summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='route',
            name='destinaton',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='route',
            name='origin',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='route',
            name='via',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trip',
            name='block',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trip',
            name='ticket_machine_code',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='BankHolidayDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('scotland', models.BooleanField(null=True)),
                ('bank_holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bustimes.bankholiday')),
            ],
        ),
    ]
