# Generated by Django 2.2.5 on 2019-10-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='stoptime',
            name='activity',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='stoptime',
            name='timing_status',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='trip',
            name='sequence',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='journey_pattern',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trip',
            name='notes',
            field=models.ManyToManyField(blank=True, to='bustimes.Note'),
        ),
    ]
