# Generated by Django 2.2.5 on 2019-10-11 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstops.StopPoint'),
        ),
        migrations.AlterIndexTogether(
            name='stoptime',
            index_together={('stop_code', 'departure')},
        ),
    ]
