# Generated by Django 4.0.1 on 2022-01-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0002_route_route_line_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
