# Generated by Django 4.2.6 on 2023-10-09 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0002_stoptime_notes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='calendar',
            new_name='bustimes_ca_start_d_3f135c_idx',
            old_fields=('start_date', 'end_date'),
        ),
        migrations.RenameIndex(
            model_name='route',
            new_name='bustimes_ro_source__a99810_idx',
            old_fields=('source', 'service_code'),
        ),
        migrations.RenameIndex(
            model_name='route',
            new_name='bustimes_ro_start_d_d04783_idx',
            old_fields=('start_date', 'end_date'),
        ),
        migrations.RenameIndex(
            model_name='stoptime',
            new_name='bustimes_st_stop_id_cde000_idx',
            old_fields=('stop', 'departure'),
        ),
        migrations.RenameIndex(
            model_name='trip',
            new_name='bustimes_tr_route_i_bc1b4a_idx',
            old_fields=('route', 'start', 'end'),
        ),
    ]
