# Generated by Django 3.1 on 2020-08-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0002_auto_20200623_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoptime',
            name='stop_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
