# Generated by Django 2.2.5 on 2019-10-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0002_auto_20191011_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendardate',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
