# Generated by Django 2.2.6 on 2019-10-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0003_auto_20191012_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='end',
            field=models.DurationField(default='PT0S'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='start',
            field=models.DurationField(default='PT0S'),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name='trip',
            index_together={('route', 'start', 'end')},
        ),
    ]
