# Generated by Django 4.0.2 on 2022-03-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0003_alter_route_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='geometry',
        ),
        migrations.AlterField(
            model_name='bankholidaydate',
            name='scotland',
            field=models.BooleanField(help_text='Yes = Scotland only, No = not Scotland, Unknown = both', null=True),
        ),
    ]
