# Generated by Django 3.1 on 2020-09-09 07:41

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0003_auto_20200811_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(editable=False, null=True, srid=4326),
        ),
    ]
