# Generated by Django 5.1.5 on 2025-01-28 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0007_sirisource_operators_and_more'),
        ('bustimes', '0001_squashed_0003_rename_calendar_start_date_end_date_bustimes_ca_start_d_3f135c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='busstops.datasource'),
        ),
        migrations.AddField(
            model_name='trip',
            name='headsign',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
