# Generated by Django 5.1.8 on 2025-04-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0004_calendar_source_trip_headsign'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='line_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='route',
            name='revision_number_context',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AlterField(
            model_name='timetabledatasource',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetabledatasource',
            name='search',
            field=models.CharField(blank=True, help_text="for BODS sources, usually one of the operator's NOCs", max_length=255),
        ),
        migrations.AlterField(
            model_name='timetabledatasource',
            name='url',
            field=models.URLField(blank=True, help_text='for non-BODS sources, i.e. Stagecoach, Passenger, or Ticketer'),
        ),
    ]
