# Generated by Django 2.2.8 on 2019-12-09 10:24

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0004_auto_20191013_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='dates',
            field=django.contrib.postgres.fields.ranges.DateRangeField(null=True),
        ),
        migrations.AddField(
            model_name='calendardate',
            name='dates',
            field=django.contrib.postgres.fields.ranges.DateRangeField(null=True),
        ),
        migrations.AddField(
            model_name='calendardate',
            name='special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route',
            name='dates',
            field=django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True),
        ),
    ]
