# Generated by Django 4.0.4 on 2022-05-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0004_remove_route_geometry_alter_bankholidaydate_scotland'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='inbound_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='route',
            name='outbound_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='route',
            name='public_use',
            field=models.BooleanField(null=True),
        ),
    ]
