# Generated by Django 3.1.4 on 2020-12-24 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vosa', '0002_auto_20201121_0959'),
        ('bustimes', '0004_auto_20201127_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vosa.registration'),
        ),
        migrations.AddField(
            model_name='route',
            name='revision_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='service_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='route',
            name='line_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
