# Generated by Django 4.1b1 on 2022-06-22 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("busstops", "0005_rename_id_operator_noc"),
        (
            "bustimes",
            "0005_route_inbound_description_route_outbound_description_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TimetableDataSource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("search", models.CharField(blank=True, max_length=255)),
                ("url", models.URLField(blank=True)),
                ("modified_at", models.DateTimeField(blank=True, null=True)),
                ("settings", models.JSONField(blank=True, null=True)),
                ("complete", models.BooleanField(default=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "operators",
                    models.ManyToManyField(blank=True, to="busstops.operator"),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="busstops.region",
                    ),
                ),
            ],
        ),
    ]
