# Generated by Django 5.2.1 on 2025-05-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0005_route_created_at_route_line_id_route_modified_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bankholidaydate',
            constraint=models.UniqueConstraint(fields=('bank_holiday', 'date'), name='unique_bank_holiday_date'),
        ),
    ]
