# Generated by Django 5.2.3 on 2025-06-18 09:10

import django.db.models.deletion
from django.db import migrations, models


def create_versions(apps, schema_editor):
    TimetableDataSource = apps.get_model("bustimes", "TimetableDataSource")
    DataSource = apps.get_model("busstops", "DataSource")
    Version = apps.get_model("bustimes", "Version")
    # db_alias = schema_editor.connection.alias
    sources = TimetableDataSource.objects
    for timetable_source in sources.filter(url__startswith="https://data.discoverpassenger.com/operator/"):
        try:
            data_source = DataSource.objects.get(url=timetable_source.url)
        except DataSource.DoesNotExist:
            continue
        data_source.source = timetable_source
        data_source.save()
        if data_source.settings:
            versions = Version.objects.bulk_create(
                [
                    Version(source=timetable_source, name=filename, start_date=start_date, end_date=end_date)
                    for filename, (start_date, end_date) in data_source.settings.items()
                ]
            )
            for version in versions:
                data_source.route_set.filter(code__startswith=version.name).update(version=version)


def remove_versions(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0006_bankholidaydate_unique_bank_holiday_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bustimes.timetabledatasource')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bustimes.version'),
        ),
        migrations.RunPython(create_versions, remove_versions)
    ]
