# Generated by Django 2.2.8 on 2019-12-20 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0048_auto_20191220_1735'),
        ('bustimes', '0006_auto_20191209_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoptime',
            name='stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.StopPoint'),
        ),
    ]
