# Generated by Django 4.0.7 on 2022-08-05 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("busstops", "0005_rename_id_operator_noc"),
        ("bustimes", "0006_timetabledatasource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="busstops.service",
            ),
        ),
        migrations.AlterField(
            model_name="stoptime",
            name="stop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="busstops.stoppoint",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="busstops.stoppoint",
            ),
        ),
    ]
