# Generated by Django 2.2.9 on 2020-01-04 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0048_auto_20191220_1735'),
        ('bustimes', '0007_stoptime_stop'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='stoptime',
            index_together={('stop', 'departure')},
        ),
    ]
