# Generated by Django 4.0.7 on 2022-08-24 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("busstops", "0007_alter_service_geometry"),
        ("bustimes", "0007_alter_route_service_alter_stoptime_stop_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="next_trip",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bustimes.trip",
            ),
        ),
        migrations.AlterIndexTogether(
            name="route",
            index_together={("source", "service_code"), ("start_date", "end_date")},
        ),
    ]
