# Generated by Django 5.2.4 on 2025-07-31 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0007_version_route_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='fri',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='mon',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='sat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='sun',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='thu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='tue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='wed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bustimes.route'),
        ),
    ]
