# Generated by Django 3.2.5 on 2021-07-22 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0007_service_public_use'),
        ('bustimes', '0007_auto_20210514_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='stoptime',
            name='activity',
        ),
        migrations.AddField(
            model_name='trip',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.operator'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bustimes.calendar'),
        ),
        migrations.RemoveField(
            model_name='trip',
            name='block',
        ),
        migrations.AddField(
            model_name='trip',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bustimes.block'),
        ),
    ]
