# Generated by Django 4.0.7 on 2022-09-21 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("busstops", "0009_alter_datasource_name_alter_datasource_url"),
        ("bustimes", "0008_trip_next_trip_alter_route_index_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="routelink",
            unique_together={("service", "from_stop", "to_stop")},
        ),
    ]
