# Generated by Django 5.2.7 on 2025-10-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0008_alter_calendar_fri_alter_calendar_mon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='block',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='headsign',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='journey_pattern',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='ticket_machine_code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicle_journey_code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
