# Generated by Django 5.2.5 on 2025-08-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0008_alter_calendar_fri_alter_calendar_mon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stoptime',
            name='stop_code',
        ),
        migrations.AddField(
            model_name='stoptime',
            name='timing_point',
            field=models.CharField(db_default=False),
        ),
    ]
