# Generated by Django 2.2.8 on 2020-01-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0008_auto_20200104_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendardate',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendardate',
            name='operation',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='calendardate',
            name='special',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='calendardate',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterIndexTogether(
            name='calendar',
            index_together={('start_date', 'end_date')},
        ),
        migrations.AlterIndexTogether(
            name='route',
            index_together={('start_date', 'end_date')},
        ),
    ]
