# Generated by Django 3.2.6 on 2021-08-24 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0009_auto_20210817_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stoptime',
            options={'ordering': ('id',)},
        ),
    ]
