# Generated by Django 4.1.5 on 2023-02-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bustimes", "0009_alter_routelink_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="vehicle_journey_code",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name="trip",
            name="_block",
            field=models.CharField(
                blank=True, db_column="block", db_index=True, max_length=100
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trip",
            name="journey_pattern",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="trip",
            name="ticket_machine_code",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
