# Generated by Django 5.2.7 on 2025-10-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0009_alter_trip_block_alter_trip_headsign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetabledatasource',
            name='notes',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='current',
            field=models.BooleanField(default=True),
        ),
    ]
