# Generated by Django 5.2.7 on 2025-10-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0011_alter_locality_slug_alter_operator_slug_and_more'),
        ('bustimes', '0010_timetabledatasource_notes_version_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetabledatasource',
            name='url',
            field=models.URLField(blank=True, help_text='for non-BODS sources, i.e. Stagecoach, Passenger, or Ticketer', verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='block',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='ticket_machine_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicle_journey_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(condition=models.Q(('vehicle_journey_code__isnull', False)), fields=['vehicle_journey_code'], name='bustimes_trip_vj_code'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(condition=models.Q(('ticket_machine_code__isnull', False)), fields=['ticket_machine_code'], name='bustimes_trip_tm_code'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(condition=models.Q(('block__isnull', False)), fields=['block'], name='bustimes_trip_block'),
        ),
    ]
