# Generated by Django 3.2.7 on 2021-09-30 19:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0010_auto_20210930_1810'),
        ('bustimes', '0010_alter_stoptime_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_metres', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('override', models.BooleanField(default=False)),
                ('from_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_from', to='busstops.stoppoint')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstops.service')),
                ('to_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_to', to='busstops.stoppoint')),
            ],
        ),
    ]
