# Generated by Django 3.2.7 on 2021-09-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0011_routelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='revision_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
