# Generated by Django 6.0.1 on 2026-02-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0011_alter_timetabledatasource_url_alter_trip_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
    ]
