# Generated by Django 6.0.3 on 2026-03-12 13:21

import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0012_route_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetabledatasource',
            name='search',
            field=models.CharField(blank=True, help_text="for BODS sources, usually one of the operator's NOCs. But remember that searching for 'ANEA' for example will return *all* Arriva datasets, not just the ANEA one", max_length=255),
        ),
    ]
