# Generated by Django 5.2.5 on 2025-08-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vosa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='authorised_discs',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='licence',
            name='discs',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
