# Generated by Django 3.1.3 on 2020-11-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vosa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='description',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='service_type_description',
        ),
        migrations.AddField(
            model_name='licence',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licence',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licence',
            name='granted_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='service_type_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='licence',
            name='authorised_discs',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='licence',
            name='discs',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_number',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
