# Generated by Django 3.2.7 on 2021-10-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vosa', '0001_squashed_0004_auto_20210913_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='licence',
            name='licence_status',
            field=models.CharField(max_length=255),
        ),
    ]
