# Generated by Django 3.2.7 on 2021-09-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vosa', '0003_auto_20210824_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='authority_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='registration',
            name='finish_point',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='registration',
            name='service_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='start_point',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='registration',
            name='subsidies_details',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
