# Generated by Django 3.2.7 on 2021-10-01 09:31

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.datetime
import django.db.models.functions.text


class Migration(migrations.Migration):

    replaces = [('vehicles', '0001_initial'), ('vehicles', '0002_auto_20200917_0133'), ('vehicles', '0003_auto_20200930_1131'), ('vehicles', '0004_auto_20201027_1204'), ('vehicles', '0005_delete_call'), ('vehicles', '0006_auto_20201121_1614'), ('vehicles', '0007_auto_20201130_1939'), ('vehicles', '0008_auto_20210104_1742'), ('vehicles', '0009_livery_text_colour'), ('vehicles', '0010_auto_20210202_1951'), ('vehicles', '0011_auto_20210204_1628'), ('vehicles', '0012_auto_20210210_1456'), ('vehicles', '0013_auto_20210218_1332'), ('vehicles', '0014_auto_20210428_1846'), ('vehicles', '0015_auto_20210817_2045'), ('vehicles', '0016_auto_20210914_1551'), ('vehicles', '0017_auto_20210930_2046')]

    initial = True

    dependencies = [
        ('bustimes', '0006_auto_20210115_1956'),
        ('bustimes', '0002_auto_20200930_1131'),
        ('bustimes', '0011_routelink'),
        ('bustimes', '0004_auto_20201127_1220'),
        ('busstops', '0007_service_public_use'),
        ('busstops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('busstops', '0006_auto_20201225_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('colours', models.CharField(blank=True, max_length=255)),
                ('css', models.CharField(blank=True, max_length=255)),
                ('horizontal', models.BooleanField(default=False)),
                ('angle', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'liveries',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('fleet_number', models.PositiveIntegerField(blank=True, null=True)),
                ('fleet_code', models.CharField(blank=True, max_length=24)),
                ('reg', models.CharField(blank=True, max_length=24)),
                ('colours', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('branding', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('withdrawn', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet_number', models.CharField(blank=True, max_length=24)),
                ('reg', models.CharField(blank=True, max_length=24)),
                ('vehicle_type', models.CharField(blank=True, max_length=255)),
                ('colours', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('branding', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('withdrawn', models.BooleanField(null=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=255)),
                ('approved', models.BooleanField(db_index=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleJourney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('route_name', models.CharField(blank=True, max_length=64)),
                ('code', models.CharField(blank=True, max_length=255)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('direction', models.CharField(blank=True, max_length=8)),
                ('data', models.JSONField(blank=True, null=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.service')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstops.datasource')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('double_decker', models.BooleanField(null=True)),
                ('coach', models.BooleanField(null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='VehicleRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('changes', models.JSONField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('from_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revision_from', to='busstops.operator')),
                ('to_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revision_to', to='busstops.operator')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('latlong', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('heading', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('early', models.SmallIntegerField(blank=True, null=True)),
                ('delay', models.SmallIntegerField(blank=True, null=True)),
                ('current', models.BooleanField(default=False)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehiclejourney')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='VehicleEditFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add', models.BooleanField(default=True)),
                ('edit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicleedit')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehiclefeature')),
            ],
        ),
        migrations.AddField(
            model_name='vehicleedit',
            name='features',
            field=models.ManyToManyField(blank=True, through='vehicles.VehicleEditFeature', to='vehicles.VehicleFeature'),
        ),
        migrations.AddField(
            model_name='vehicleedit',
            name='livery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.livery'),
        ),
        migrations.AddField(
            model_name='vehicleedit',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='features',
            field=models.ManyToManyField(blank=True, to='vehicles.VehicleFeature'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='latest_location',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_vehicle', to='vehicles.vehiclelocation'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='livery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.livery'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.operator'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='busstops.datasource'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicletype'),
        ),
        migrations.CreateModel(
            name='JourneyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=64)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.datasource')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.service')),
                ('siri_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.sirisource')),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.PositiveSmallIntegerField()),
                ('aimed_arrival_time', models.DateTimeField(null=True)),
                ('expected_arrival_time', models.DateTimeField(null=True)),
                ('aimed_departure_time', models.DateTimeField(null=True)),
                ('expected_departure_time', models.DateTimeField(null=True)),
                ('journey', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehiclejourney')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busstops.stoppoint')),
            ],
        ),
        migrations.AddIndex(
            model_name='vehiclelocation',
            index=models.Index(condition=models.Q(('current', True)), fields=['datetime'], name='datetime'),
        ),
        migrations.AddIndex(
            model_name='vehiclelocation',
            index=models.Index(condition=models.Q(('current', True)), fields=['datetime', 'latlong'], name='datetime_latlong'),
        ),
        migrations.AlterUniqueTogether(
            name='vehiclejourney',
            unique_together={('vehicle', 'datetime')},
        ),
        migrations.AlterIndexTogether(
            name='vehiclejourney',
            index_together={('service', 'datetime')},
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('code', 'operator')},
        ),
        migrations.AlterUniqueTogether(
            name='journeycode',
            unique_together={('code', 'service', 'siri_source'), ('code', 'service', 'data_source')},
        ),
        migrations.AddField(
            model_name='vehicleedit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiclerevision',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiclejourney',
            name='trip',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bustimes.trip'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fleet_code',
            field=models.CharField(blank=True, db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='reg',
            field=models.CharField(blank=True, db_index=True, max_length=24),
        ),
        migrations.RemoveField(
            model_name='vehicleedit',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='vehicleedit',
            name='username',
        ),
        migrations.RemoveField(
            model_name='vehiclerevision',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='vehiclerevision',
            name='username',
        ),
        migrations.AddField(
            model_name='livery',
            name='left_css',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='livery',
            name='right_css',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='livery',
            name='white_text',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Call',
        ),
        migrations.AddField(
            model_name='vehiclerevision',
            name='from_livery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revision_from', to='vehicles.livery'),
        ),
        migrations.AddField(
            model_name='vehiclerevision',
            name='from_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revision_from', to='vehicles.vehicletype'),
        ),
        migrations.AddField(
            model_name='vehiclerevision',
            name='to_livery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revision_to', to='vehicles.livery'),
        ),
        migrations.AddField(
            model_name='vehiclerevision',
            name='to_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revision_to', to='vehicles.vehicletype'),
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='occupancy',
            field=models.CharField(blank=True, choices=[('seatsAvailable', 'Seats available'), ('standingAvailable', 'Standing available'), ('full', 'Full')], max_length=17),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='electric',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='livery',
            name='text_colour',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='latest_location',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehiclelocation'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.datasource'),
        ),
        migrations.RemoveIndex(
            model_name='vehiclelocation',
            name='datetime',
        ),
        migrations.RemoveIndex(
            model_name='vehiclelocation',
            name='datetime_latlong',
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='occupancy_thresholds',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='seated_capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='seated_occupancy',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='wheelchair_capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='wheelchair_occupancy',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='garage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bustimes.garage'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='latest_journey',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_vehicle', to='vehicles.vehiclejourney'),
        ),
        migrations.AlterIndexTogether(
            name='vehiclejourney',
            index_together=set(),
        ),
        migrations.AddIndex(
            model_name='vehiclejourney',
            index=models.Index(django.db.models.expressions.F('service'), django.db.models.expressions.OrderBy(django.db.models.functions.datetime.TruncDate('datetime')), name='service_datetime_date'),
        ),
        migrations.AlterField(
            model_name='vehiclerevision',
            name='from_livery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='revision_from', to='vehicles.livery'),
        ),
        migrations.AlterField(
            model_name='vehiclerevision',
            name='from_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='revision_from', to='busstops.operator'),
        ),
        migrations.AlterField(
            model_name='vehiclerevision',
            name='from_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='revision_from', to='vehicles.vehicletype'),
        ),
        migrations.AlterField(
            model_name='vehiclerevision',
            name='to_livery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='revision_to', to='vehicles.livery'),
        ),
        migrations.AlterField(
            model_name='vehiclerevision',
            name='to_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='revision_to', to='busstops.operator'),
        ),
        migrations.AlterField(
            model_name='vehiclerevision',
            name='to_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='revision_to', to='vehicles.vehicletype'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fleet_code',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='reg',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(django.db.models.functions.text.Upper('fleet_code'), name='fleet_code'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(django.db.models.functions.text.Upper('reg'), name='reg'),
        ),
        migrations.AlterField(
            model_name='vehiclejourney',
            name='trip',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bustimes.trip'),
        ),
    ]
