# Generated by Django 4.2.6 on 2023-10-09 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vehiclecode',
            new_name='vehicles_ve_code_73ff06_idx',
            old_fields=('code', 'scheme'),
        ),
    ]
