# Generated by Django 3.0.7 on 2020-06-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelocation',
            name='capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='occupied',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
