# Generated by Django 2.1.4 on 2018-12-27 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20181223_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclelocation',
            name='data',
        ),
    ]
