# Generated by Django 3.1.1 on 2020-09-30 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0002_auto_20200930_1131'),
        ('vehicles', '0002_auto_20200917_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclejourney',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bustimes.trip'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fleet_code',
            field=models.CharField(blank=True, db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='reg',
            field=models.CharField(blank=True, db_index=True, max_length=24),
        ),
    ]
