# Generated by Django 3.2.8 on 2021-10-29 18:01

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0002_route_route_line_name'),
        ('vehicles', '0002_auto_20211002_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclejourney',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bustimes.trip'),
        ),
        migrations.AddIndex(
            model_name='vehiclejourney',
            index=models.Index(django.db.models.expressions.F('vehicle'), django.db.models.expressions.OrderBy(django.db.models.functions.datetime.TruncDate('datetime')), name='vehicle_datetime_date'),
        ),
    ]
