# Generated by Django 3.0.8 on 2020-07-11 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20200615_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclelocation',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='vehiclelocation',
            name='occupied',
        ),
    ]
