# Generated by Django 5.0.2 on 2024-02-21 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_squashed_0003_sirisubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclerevision',
            old_name='datetime',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='vehiclerevision',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclerevision',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiclerevision',
            name='pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclerevision',
            name='disapproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclerevision',
            name='score',
            field=models.SmallIntegerField(default=0),
        ),
    ]
