# Generated by Django 2.1.5 on 2019-01-27 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_remove_vehiclelocation_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclejourney',
            options={'ordering': ('id',)},
        ),
        migrations.AlterIndexTogether(
            name='vehiclelocation',
            index_together={('current', 'datetime')},
        ),
    ]
