# Generated by Django 3.1.2 on 2020-10-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_auto_20200930_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleedit',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='vehicleedit',
            name='username',
        ),
        migrations.RemoveField(
            model_name='vehiclerevision',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='vehiclerevision',
            name='username',
        ),
        migrations.AddField(
            model_name='livery',
            name='left_css',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='livery',
            name='right_css',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='livery',
            name='white_text',
            field=models.BooleanField(default=False),
        ),
    ]
