# Generated by Django 2.1.5 on 2019-01-28 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_auto_20190127_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclejourney',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.Vehicle'),
        ),
    ]
