# Generated by Django 3.1.2 on 2020-10-30 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_auto_20201027_1204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Call',
        ),
    ]
