# Generated by Django 3.2.10 on 2021-12-20 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehiclecode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='latest_location',
        ),
        migrations.DeleteModel(
            name='VehicleLocation',
        ),
    ]
