# Generated by Django 5.0.2 on 2024-02-29 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_rename_datetime_vehiclerevision_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerevision',
            name='disapproved_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclerevision',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='vehicleeditvote',
            unique_together={('by_user', 'for_edit'), ('by_user', 'for_revision')},
        ),
    ]
