# Generated by Django 3.1 on 2020-08-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_auto_20200811_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclejourney',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclejourney',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
