# Generated by Django 4.0.2 on 2022-02-14 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_auto_20211220_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRevisionFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add', models.BooleanField(default=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehiclefeature')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='latest_journey_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclerevision',
            name='features',
            field=models.ManyToManyField(blank=True, through='vehicles.VehicleRevisionFeature', to='vehicles.VehicleFeature'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='branding',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehiclerevisionfeature',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehiclerevision'),
        ),
    ]
