# Generated by Django 5.0.2 on 2024-03-04 17:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_vehiclerevision_disapproved_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleedit',
            name='arbiter',
        ),
        migrations.RemoveField(
            model_name='vehicleedit',
            name='features',
        ),
        migrations.RemoveField(
            model_name='vehicleedit',
            name='livery',
        ),
        migrations.RemoveField(
            model_name='vehicleedit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vehicleedit',
            name='vehicle',
        ),
        migrations.AlterUniqueTogether(
            name='vehicleeditvote',
            unique_together={('by_user', 'for_revision')},
        ),
        migrations.DeleteModel(
            name='VehicleEditFeature',
        ),
        migrations.RemoveField(
            model_name='vehicleeditvote',
            name='for_edit',
        ),
        migrations.DeleteModel(
            name='VehicleEdit',
        ),
    ]
