# Generated by Django 3.1 on 2020-08-27 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_auto_20200825_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclejourney',
            name='text',
        ),
    ]
