# Generated by Django 2.1.7 on 2019-04-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_auto_20190128_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclejourney',
            name='route_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
