# Generated by Django 4.0.2 on 2022-03-16 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0004_alter_locality_parent_alter_place_parent_and_more'),
        ('vehicles', '0006_vehiclerevisionfeature_vehicle_latest_journey_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livery',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livery',
            name='colours',
            field=models.CharField(blank=True, help_text="Keep it simple. Being able to read the route number on the map the is much more important than 'accuracy'", max_length=255),
        ),
        migrations.AlterField(
            model_name='livery',
            name='css',
            field=models.CharField(blank=True, help_text='Most liveries can be adequately represented with a list of colours and an angle,\nin which case you should leave this blank', max_length=255, verbose_name='CSS'),
        ),
        migrations.AlterField(
            model_name='livery',
            name='horizontal',
            field=models.BooleanField(default=False, help_text='Equivalent to setting the angle to 90'),
        ),
        migrations.AlterField(
            model_name='livery',
            name='left_css',
            field=models.CharField(blank=True, help_text='Automatically generated from colours and angle if CSS field is blank', max_length=255, verbose_name='Left CSS'),
        ),
        migrations.AlterField(
            model_name='livery',
            name='right_css',
            field=models.CharField(blank=True, help_text='Automatically generated colours and angle if CSS field is blank', max_length=255, verbose_name='Right CSS'),
        ),
        migrations.AlterField(
            model_name='livery',
            name='text_colour',
            field=models.CharField(blank=True, editable=False, max_length=7),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='branding',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiclerevision',
            name='from_livery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_from', to='vehicles.livery'),
        ),
        migrations.AlterField(
            model_name='vehiclerevision',
            name='from_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_from', to='busstops.operator'),
        ),
        migrations.AlterField(
            model_name='vehiclerevision',
            name='from_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_from', to='vehicles.vehicletype'),
        ),
        migrations.AlterField(
            model_name='vehiclerevision',
            name='to_livery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_to', to='vehicles.livery'),
        ),
        migrations.AlterField(
            model_name='vehiclerevision',
            name='to_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_to', to='busstops.operator'),
        ),
        migrations.AlterField(
            model_name='vehiclerevision',
            name='to_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_to', to='vehicles.vehicletype'),
        ),
    ]
