# Generated by Django 3.1.3 on 2020-11-30 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0004_auto_20201127_1220'),
        ('vehicles', '0006_auto_20201121_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclejourney',
            name='trip',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bustimes.trip'),
        ),
    ]
