# Generated by Django 5.0.4 on 2024-05-08 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_remove_vehicleedit_arbiter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallivery',
            name='locked',
        ),
        migrations.RemoveField(
            model_name='livery',
            name='locked',
        ),
        migrations.RemoveField(
            model_name='livery',
            name='operators',
        ),
    ]
