# Generated by Django 2.2 on 2019-04-09 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0039_auto_20190401_1253'),
        ('vehicles', '0006_vehiclejourney_route_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('colours', models.CharField(blank=True, max_length=255)),
                ('css', models.CharField(blank=True, max_length=255)),
                ('horizontal', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='usb',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='wifi',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='vehiclejourney',
            name='direction',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.CreateModel(
            name='JourneyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=64)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.DataSource')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.Service')),
                ('siri_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.SIRISource')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='livery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.Livery'),
        ),
    ]
