# Generated by Django 5.0.6 on 2024-05-22 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0003_alter_stopcode_source'),
        ('vehicles', '0007_remove_historicallivery_locked_remove_livery_locked_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vehiclerevision',
            constraint=models.UniqueConstraint(condition=models.Q(('pending', True)), fields=('to_operator',), name='unique_pending_operator'),
        ),
        migrations.AddConstraint(
            model_name='vehiclerevision',
            constraint=models.UniqueConstraint(condition=models.Q(('pending', True)), fields=('to_type',), name='unique_pending_type'),
        ),
        migrations.AddConstraint(
            model_name='vehiclerevision',
            constraint=models.UniqueConstraint(condition=models.Q(('pending', True)), fields=('to_livery',), name='unique_pending_livery'),
        ),
    ]
