# Generated by Django 3.1.5 on 2021-01-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_auto_20201130_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='occupancy',
            field=models.CharField(blank=True, choices=[('seatsAvailable', 'Seats available'), ('standingAvailable', 'Standing available'), ('full', 'Full')], max_length=17),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='electric',
            field=models.BooleanField(null=True),
        ),
    ]
