# Generated by Django 4.0.2 on 2022-03-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_livery_updated_at_alter_livery_colours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livery',
            name='stroke_colour',
            field=models.CharField(blank=True, editable=False, max_length=7),
        ),
        migrations.AlterField(
            model_name='livery',
            name='colours',
            field=models.CharField(blank=True, help_text="Keep it simple. Being able to read the route number on the map the is much more important than 'accuracy'", max_length=512),
        ),
        migrations.AlterField(
            model_name='livery',
            name='css',
            field=models.CharField(blank=True, help_text='Most liveries can be adequately represented with a list of colours and an angle,\nin which case you should leave this blank', max_length=1024, verbose_name='CSS'),
        ),
        migrations.AlterField(
            model_name='livery',
            name='left_css',
            field=models.CharField(blank=True, help_text='Automatically generated from colours and angle if CSS field is blank', max_length=1024, verbose_name='Left CSS'),
        ),
        migrations.AlterField(
            model_name='livery',
            name='right_css',
            field=models.CharField(blank=True, help_text='Automatically generated colours and angle if CSS field is blank', max_length=1024, verbose_name='Right CSS'),
        ),
    ]
