# Generated by Django 4.0.3 on 2022-03-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_livery_stroke_colour_alter_livery_colours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livery',
            name='published',
            field=models.BooleanField(default=True, help_text='Tick to include in the CSS and be able to apply this livery to vehicles'),
            preserve_default=False,
        ),
    ]
