# Generated by Django 3.1.5 on 2021-01-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_auto_20210104_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='livery',
            name='text_colour',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
