# Generated by Django 5.0.6 on 2024-05-25 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0003_alter_stopcode_source'),
        ('vehicles', '0008_vehiclerevision_unique_pending_operator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehiclerevision',
            name='unique_pending_operator',
        ),
        migrations.RemoveConstraint(
            model_name='vehiclerevision',
            name='unique_pending_type',
        ),
        migrations.RemoveConstraint(
            model_name='vehiclerevision',
            name='unique_pending_livery',
        ),
        migrations.AddConstraint(
            model_name='vehiclerevision',
            constraint=models.UniqueConstraint(condition=models.Q(('pending', True)), fields=('vehicle', 'to_operator'), name='unique_pending_operator'),
        ),
        migrations.AddConstraint(
            model_name='vehiclerevision',
            constraint=models.UniqueConstraint(condition=models.Q(('pending', True)), fields=('vehicle', 'to_type'), name='unique_pending_type'),
        ),
        migrations.AddConstraint(
            model_name='vehiclerevision',
            constraint=models.UniqueConstraint(condition=models.Q(('pending', True)), fields=('vehicle', 'to_livery'), name='unique_pending_livery'),
        ),
    ]
