# Generated by Django 3.1 on 2020-09-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleedit',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclerevision',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
