# Generated by Django 3.1.6 on 2021-02-02 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0006_auto_20201225_0004'),
        ('vehicles', '0009_livery_text_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='latest_location',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehiclelocation'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.datasource'),
        ),
    ]
