# Generated by Django 5.1.4 on 2024-12-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_remove_vehiclerevision_unique_pending_operator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallivery',
            name='css',
        ),
        migrations.RemoveField(
            model_name='livery',
            name='css',
        ),
        migrations.AlterField(
            model_name='historicallivery',
            name='colours',
            field=models.CharField(blank=True, help_text='Left and right CSS will be generated from this', max_length=512),
        ),
        migrations.AlterField(
            model_name='historicallivery',
            name='right_css',
            field=models.CharField(blank=True, help_text='Should be a mirror image of the left CSS', max_length=1024, verbose_name='Right CSS'),
        ),
        migrations.AlterField(
            model_name='livery',
            name='colours',
            field=models.CharField(blank=True, help_text='Left and right CSS will be generated from this', max_length=512),
        ),
        migrations.AlterField(
            model_name='livery',
            name='right_css',
            field=models.CharField(blank=True, help_text='Should be a mirror image of the left CSS', max_length=1024, verbose_name='Right CSS'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='style',
            field=models.CharField(blank=True, choices=[('double decker', 'double decker'), ('minibus', 'minibus'), ('coach', 'coach'), ('articulated', 'articulated'), ('train', 'train'), ('tram', 'tram'), ('amphibious', 'amphibious')], max_length=13),
        ),
    ]
