# Generated by Django 4.0.3 on 2022-04-05 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0004_alter_locality_parent_alter_place_parent_and_more'),
        ('vehicles', '0009_livery_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclejourney',
            name='data',
        ),
        migrations.AlterField(
            model_name='livery',
            name='colours',
            field=models.CharField(blank=True, help_text="Keep it simple.\nSimplicity (and being able to read the route number on the map) is much more important than 'accuracy'.", max_length=512),
        ),
        migrations.AlterField(
            model_name='livery',
            name='css',
            field=models.CharField(blank=True, help_text='Leave this blank.\nA livery can be adequately represented with a list of colours and an angle.', max_length=1024, verbose_name='CSS'),
        ),
        migrations.AlterField(
            model_name='livery',
            name='left_css',
            field=models.CharField(blank=True, help_text='Automatically generated from colours and angle', max_length=1024, verbose_name='Left CSS'),
        ),
        migrations.AlterField(
            model_name='livery',
            name='operator',
            field=models.ForeignKey(blank=True, help_text="A livery may be assigned to vehicles from more than one operator.\nYou can use this field to make this livery selectable for a new operator – that's its only purpose", null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.operator'),
        ),
        migrations.AlterField(
            model_name='livery',
            name='right_css',
            field=models.CharField(blank=True, help_text='Automatically generated from colours and angle', max_length=1024, verbose_name='Right CSS'),
        ),
        migrations.AlterField(
            model_name='livery',
            name='stroke_colour',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='livery',
            name='text_colour',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
