# Generated by Django 3.1 on 2020-09-09 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0006_delete_note'),
        ('vehicles', '0009_auto_20200901_1734'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='call',
            unique_together={('journey', 'visit_number')},
        ),
        migrations.AlterUniqueTogether(
            name='vehiclejourney',
            unique_together={('vehicle', 'datetime')},
        ),
        migrations.AlterIndexTogether(
            name='vehiclejourney',
            index_together={('service', 'datetime')},
        ),
    ]
