# Generated by Django 2.2.4 on 2019-08-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_vehicleedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='livery',
            name='angle',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclelocation',
            name='heading',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
