# Generated by Django 3.1.1 on 2020-09-16 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_auto_20200910_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleedit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vehiclerevision',
            name='user',
        ),
    ]
