# Generated by Django 3.1.6 on 2021-02-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_auto_20210204_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelocation',
            name='occupancy_thresholds',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='seated_capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='seated_occupancy',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='wheelchair_capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='wheelchair_occupancy',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
