# Generated by Django 5.1.8 on 2025-04-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_historicallivery_show_name_livery_show_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallivery',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='livery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
