# Generated by Django 4.0.4 on 2022-04-16 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('busstops', '0004_alter_locality_parent_alter_place_parent_and_more'),
        ('vehicles', '0011_vehicleedit_arbiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLivery',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('colours', models.CharField(blank=True, help_text="Keep it simple.\nSimplicity (and being able to read the route number on the map) is much more important than 'accuracy'.", max_length=512)),
                ('css', models.CharField(blank=True, help_text='Leave this blank.\nA livery can be adequately represented with a list of colours and an angle.', max_length=1024, verbose_name='CSS')),
                ('left_css', models.CharField(blank=True, help_text='Automatically generated from colours and angle', max_length=1024, verbose_name='Left CSS')),
                ('right_css', models.CharField(blank=True, help_text='Automatically generated from colours and angle', max_length=1024, verbose_name='Right CSS')),
                ('white_text', models.BooleanField(default=False)),
                ('text_colour', models.CharField(blank=True, max_length=7)),
                ('stroke_colour', models.CharField(blank=True, max_length=7)),
                ('horizontal', models.BooleanField(default=False, help_text='Equivalent to setting the angle to 90')),
                ('angle', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField(help_text='Tick to include in the CSS and be able to apply this livery to vehicles')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, db_constraint=False, help_text="A livery may be assigned to vehicles from more than one operator.\nYou can use this field to make this livery selectable for a new operator – that's its only purpose", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='busstops.operator')),
            ],
            options={
                'verbose_name': 'historical livery',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
