# Generated by Django 2.2.4 on 2019-09-03 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0044_auto_20190803_1042'),
        ('vehicles', '0012_auto_20190903_0042'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='vehiclejourney',
            index_together={('service', 'datetime'), ('vehicle', 'datetime')},
        ),
    ]
