# Generated by Django 5.1.8 on 2025-05-02 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_alter_historicallivery_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclerevision',
            name='score',
        ),
        migrations.DeleteModel(
            name='VehicleEditVote',
        ),
    ]
