# Generated by Django 4.0.4 on 2022-05-12 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0005_route_inbound_description_route_outbound_description_and_more'),
        ('vehicles', '0012_historicallivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclejourney',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bustimes.block'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='latest_journey',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_vehicle', to='vehicles.vehiclejourney'),
        ),
        migrations.DeleteModel(
            name='JourneyCode',
        ),
    ]
