# Generated by Django 2.2.5 on 2019-09-04 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0044_auto_20190803_1042'),
        ('vehicles', '0013_auto_20190903_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='stop',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='busstops.StopPoint'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='call',
            name='aimed_arrival_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='aimed_departure_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='expected_arrival_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='expected_departure_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterIndexTogether(
            name='call',
            index_together={('stop', 'expected_departure_time')},
        ),
    ]
