# Generated by Django 4.1b1 on 2022-06-22 12:30

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0013_vehiclejourney_block_alter_vehicle_latest_journey_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicallivery",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical livery",
                "verbose_name_plural": "historical liveries",
            },
        ),
        migrations.AlterUniqueTogether(
            name="vehicle",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="historicallivery",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Upper("code"),
                django.db.models.functions.text.Upper("operator"),
                name="vehicle_operator_and_code",
            ),
        ),
    ]
