# Generated by Django 5.2.5 on 2025-08-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0013_remove_vehiclerevision_score_delete_vehicleeditvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirisubscription',
            name='name',
            field=models.CharField(blank=True, help_text='There should be a DataSource with the same name as this', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiclejourney',
            name='direction',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
