# Generated by Django 5.2.7 on 2025-10-17 09:16

import busstops.fields
import django.db.models.deletion
import vehicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0011_alter_locality_slug_alter_operator_slug_and_more'),
        ('bustimes', '0009_alter_trip_block_alter_trip_headsign_and_more'),
        ('vehicles', '0014_alter_sirisubscription_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclejourney',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='slug',
            field=busstops.fields.AutoSlugField(editable=True, populate_from=vehicles.models.vehicle_slug, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiclejourney',
            name='service',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.service'),
        ),
        migrations.AlterField(
            model_name='vehiclejourney',
            name='vehicle',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='style',
            field=models.CharField(blank=True, choices=[('', 'single decker'), ('double decker', 'double decker'), ('minibus', 'minibus'), ('coach', 'coach'), ('decker coach', 'double decker coach'), ('articulated', 'bendy bus'), ('train', 'train'), ('tram', 'tram'), ('amphibious', 'amphibious')], max_length=13),
        ),
        migrations.AddIndex(
            model_name='vehiclejourney',
            index=models.Index(models.F('service'), models.F('date'), condition=models.Q(('date__isnull', False)), name='service_date'),
        ),
        migrations.AddIndex(
            model_name='vehiclejourney',
            index=models.Index(models.F('vehicle'), models.F('date'), condition=models.Q(('date__isnull', False), ('vehicle__isnull', False)), name='vehicle_date'),
        ),
    ]
