# Generated by Django 4.0.7 on 2022-08-06 00:54

import autoslug.fields
from django.db import migrations
import vehicles.models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0014_alter_historicallivery_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=True,
                null=True,
                populate_from=vehicles.models.vehicle_slug,
                unique=True,
            ),
        ),
    ]
