# Generated by Django 5.2.7 on 2025-10-16 10:34

import busstops.fields
import vehicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0014_alter_sirisubscription_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclejourney',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclejourney',
            name='inbound',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='slug',
            field=busstops.fields.AutoSlugField(editable=True, populate_from=vehicles.models.vehicle_slug, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiclejourney',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclejourney',
            name='direction',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
