# Generated by Django 3.2.7 on 2021-09-14 14:51

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0015_auto_20210817_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fleet_code',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='reg',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(django.db.models.functions.text.Upper('fleet_code'), name='fleet_code'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(django.db.models.functions.text.Upper('reg'), name='reg'),
        ),
    ]
