# Generated by Django 2.2.5 on 2019-09-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0015_auto_20190904_1114'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vehiclelocation',
            name='datetime',
        ),
        migrations.AddIndex(
            model_name='vehiclelocation',
            index=models.Index(condition=models.Q(current=True), fields=['current', 'datetime'], name='datetime'),
        ),
    ]
