# Generated by Django 5.2.7 on 2025-10-18 11:59

import django.db.models.deletion
from django.db import migrations, models
from django.contrib.postgres.operations import AddIndexConcurrently, RemoveIndexConcurrently


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0011_alter_locality_slug_alter_operator_slug_and_more'),
        ('bustimes', '0009_alter_trip_block_alter_trip_headsign_and_more'),
        ('vehicles', '0015_vehiclejourney_date_alter_vehicle_slug_and_more'),
    ]

    atomic = False

    operations = [
        AddIndexConcurrently(
            model_name='vehiclejourney',
            index=models.Index(models.F('service'), models.F('date'), name='vehiclejourney_service_date'),
        ),
        AddIndexConcurrently(
            model_name='vehiclejourney',
            index=models.Index(models.F('vehicle'), models.F('date'), condition=models.Q(('vehicle__isnull', False)), name='vehiclejourney_vehicle_date'),
        ),
        AddIndexConcurrently(
            model_name='vehiclejourney',
            index=models.Index(models.F('trip'), models.F('date'), condition=models.Q(('trip__isnull', False)), name='vehiclejourney_trip_date'),
        ),
        RemoveIndexConcurrently(
            model_name='vehiclejourney',
            name='service_datetime_date',
        ),
        RemoveIndexConcurrently(
            model_name='vehiclejourney',
            name='vehicle_datetime_date',
        ),
        RemoveIndexConcurrently(
            model_name='vehiclejourney',
            name='service_date',
        ),
        RemoveIndexConcurrently(
            model_name='vehiclejourney',
            name='vehicle_date',
        ),
        migrations.operations.SeparateDatabaseAndState(
            state_operations=[migrations.AlterField(
                model_name='vehiclejourney',
                name='service',
                field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busstops.service'),
            )],
            database_operations=[migrations.RunSQL(
                'DROP INDEX CONCURRENTLY IF EXISTS vehicles_vehiclejourney_service_id_b5ad5fe9',
                'CREATE INDEX CONCURRENTLY vehicles_vehiclejourney_service_id_b5ad5fe9 ON "vehicles_vehicle" ("service_id")'
            )]
        ),
        migrations.operations.SeparateDatabaseAndState(
            state_operations=[migrations.AlterField(
                model_name='vehiclejourney',
                name='trip',
                field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bustimes.trip'),
            )],
            database_operations=[migrations.RunSQL(
                'DROP INDEX CONCURRENTLY IF EXISTS vehicles_vehiclejourney_trip_id_f6cf407e',
                'CREATE INDEX CONCURRENTLY vehicles_vehiclejourney_trip_id_f6cf407e ON "vehicles_vehicle" ("trip_id")'
            )]
        ),
        migrations.operations.SeparateDatabaseAndState(
            state_operations=[migrations.AlterField(
                model_name='vehiclejourney',
                name='vehicle',
                field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle'),
            )],
            database_operations=[migrations.RunSQL(
                'DROP INDEX CONCURRENTLY IF EXISTS vehicles_vehiclejourney_vehicle_id_41154c8a',
                'CREATE INDEX CONCURRENTLY vehicles_vehiclejourney_vehicle_id_41154c8a ON "vehicles_vehicle" ("vehicle_id")'
            )]
        ),
    ]
