# Generated by Django 5.2.7 on 2025-10-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0016_remove_vehiclejourney_service_datetime_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehiclejourney',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='vehiclejourney',
            name='date',
            field=models.DateField(),
        ),
    ]
