# Generated by Django 3.2.7 on 2021-09-30 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0011_routelink'),
        ('vehicles', '0016_auto_20210914_1551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.AlterField(
            model_name='vehiclejourney',
            name='trip',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bustimes.trip'),
        ),
    ]
