# Generated by Django 2.2.5 on 2019-09-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0016_auto_20190909_1715'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vehiclelocation',
            index=models.Index(condition=models.Q(current=True), fields=['current', 'datetime', 'latlong'], name='datetime_latlong'),
        ),
    ]
