# Generated by Django 4.1.4 on 2022-12-09 17:01

import autoslug.fields
from django.db import migrations

import vehicles.models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0016_vehiclejourney_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="",
                editable=True,
                populate_from=vehicles.models.vehicle_slug,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
