# Generated by Django 2.2.5 on 2019-09-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0017_auto_20190911_0918'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vehiclelocation',
            name='datetime',
        ),
        migrations.RemoveIndex(
            model_name='vehiclelocation',
            name='datetime_latlong',
        ),
        migrations.AddIndex(
            model_name='vehiclelocation',
            index=models.Index(condition=models.Q(current=True), fields=['datetime'], name='datetime'),
        ),
        migrations.AddIndex(
            model_name='vehiclelocation',
            index=models.Index(condition=models.Q(current=True), fields=['datetime', 'latlong'], name='datetime_latlong'),
        ),
    ]
