# Generated by Django 4.1.4 on 2022-12-10 08:05

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0017_alter_vehicle_slug"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="vehicle",
            name="vehicle_operator_and_code",
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["operator", "withdrawn"], name="operator_withdrawn"
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Upper("code"),
                models.F("operator"),
                name="vehicle_operator_and_code",
            ),
        ),
    ]
