# Generated by Django 5.2.7 on 2025-10-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0011_alter_locality_slug_alter_operator_slug_and_more'),
        ('bustimes', '0011_alter_timetabledatasource_url_alter_trip_block_and_more'),
        ('vehicles', '0017_alter_vehiclejourney_unique_together_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vehiclejourney',
            index=models.Index(models.F('route_name'), models.F('date'), condition=models.Q(('service__isnull', True)), name='route_name__date'),
        ),
    ]
