# Generated by Django 2.2.5 on 2019-09-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0018_auto_20190917_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='branding',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vehicleedit',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicleedit',
            name='branding',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vehicleedit',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicleedit',
            name='features',
            field=models.ManyToManyField(blank=True, to='vehicles.VehicleFeature'),
        ),
        migrations.AddField(
            model_name='vehicleedit',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vehicleedit',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vehicleedit',
            name='user',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vehicleedit',
            name='withdrawn',
            field=models.BooleanField(default=False),
        ),
    ]
