# Generated by Django 4.1.5 on 2023-02-08 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0018_remove_vehicle_vehicle_operator_and_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehiclejourney",
            name="block",
        ),
    ]
