# Generated by Django 5.2.8 on 2025-11-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0018_vehiclejourney_route_name__date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sirisubscription',
            name='password',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='sirisubscription',
            name='producer_url',
            field=models.URLField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='sirisubscription',
            name='requestor_ref',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='sirisubscription',
            name='username',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
