# Generated by Django 2.2.7 on 2019-11-17 18:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0019_auto_20190922_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fleet_code',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='withdrawn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicleedit',
            name='changes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='delay',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclelocation',
            name='early',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclelocation',
            name='heading',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
