# Generated by Django 6.0 on 2025-12-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0019_sirisubscription_password_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vehiclecode',
            constraint=models.UniqueConstraint(fields=('code', 'scheme'), name='unique_vehicle_code'),
        ),
    ]
