# Generated by Django 2.2.8 on 2019-12-09 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bustimes', '0006_auto_20191209_1257'),
        ('vehicles', '0020_auto_20191117_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclejourney',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bustimes.Trip'),
        ),
        migrations.AlterField(
            model_name='vehiclejourney',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.Vehicle'),
        ),
    ]
