# Generated by Django 4.2 on 2023-04-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("busstops", "0014_alter_datasource_options"),
        ("vehicles", "0020_alter_vehiclefeature_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallivery",
            name="locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="livery",
            name="locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="livery",
            name="operators",
            field=models.ManyToManyField(
                blank=True, related_name="liveries", to="busstops.operator"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="locked",
            field=models.BooleanField(default=False),
        ),
    ]
