# Generated by Django 2.2.9 on 2020-01-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0021_auto_20191209_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleedit',
            name='fleet_number',
            field=models.CharField(blank=True, default='', max_length=24),
            preserve_default=False,
        ),
    ]
