# Generated by Django 4.2 on 2023-04-15 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0021_historicallivery_locked_livery_locked_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicallivery",
            name="operator",
        ),
        migrations.RemoveField(
            model_name="livery",
            name="operator",
        ),
    ]
