# Generated by Django 4.2 on 2023-05-04 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0022_remove_historicallivery_operator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleeditvote",
            name="for_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vehicles.vehiclerevision",
            ),
        ),
        migrations.AddField(
            model_name="vehicletype",
            name="fuel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("diesel", "diesel"),
                    ("electric", "electric"),
                    ("hybrid", "hybrid"),
                    ("hydrogen", "hydrogen"),
                    ("gas", "gas"),
                ],
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="vehicletype",
            name="style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("double decker", "double decker"),
                    ("minibus", "minibus"),
                    ("coach", "coach"),
                    ("articulated", "articulated"),
                    ("train", "train"),
                    ("tram", "tram"),
                ],
                max_length=13,
            ),
        ),
        migrations.AlterField(
            model_name="vehiclecode",
            name="code",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="vehicleeditvote",
            name="for_edit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vehicles.vehicleedit",
            ),
        ),
    ]
