# Generated by Django 2.2.9 on 2020-01-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0022_auto_20200106_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclejourney',
            name='trip',
        ),
    ]
