# Generated by Django 4.2.3 on 2023-07-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0023_vehicleeditvote_for_revision_vehicletype_fuel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicletype",
            name="coach",
        ),
        migrations.RemoveField(
            model_name="vehicletype",
            name="double_decker",
        ),
        migrations.RemoveField(
            model_name="vehicletype",
            name="electric",
        ),
        migrations.AddField(
            model_name="historicallivery",
            name="colour",
            field=models.CharField(
                default="",
                help_text="For the most simplified version of the livery",
                max_length=7,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="livery",
            name="colour",
            field=models.CharField(
                default="",
                help_text="For the most simplified version of the livery",
                max_length=7,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicallivery",
            name="stroke_colour",
            field=models.CharField(
                blank=True, help_text="Use sparingly, often looks shit", max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="livery",
            name="stroke_colour",
            field=models.CharField(
                blank=True, help_text="Use sparingly, often looks shit", max_length=7
            ),
        ),
    ]
