# Generated by Django 2.2.9 on 2020-02-06 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0023_remove_vehiclejourney_trip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleedit',
            old_name='user',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='vehicleedit',
            name='approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='vehicleedit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicleedit',
            name='withdrawn',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='coach',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='double_decker',
            field=models.BooleanField(null=True),
        ),
    ]
