# Generated by Django 2.2.12 on 2020-04-16 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0026_auto_20200229_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleedit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
